org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Fabric
minecraft_version=26.2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# O mod
mod_version=4.2.3.5
maven_group=net.thaumcraft
archives_base_name=thaumcraft

# Dependências
fabric_api_version=0.160.0+26.2
