package net.thaumcraft.mortuorum;

import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.crafting.Ingredient;
import net.minecraft.world.level.block.Blocks;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * O que a Máquina de Costura sabe fazer: o {@code CraftingManagerSewing} do Necromancy.
 *
 * <p><b>Arquivo gerado</b> por {@code scratchpad/am-costura.js} a partir do jar original — não se escreve à
 * mão. Cada peça de corpo sai do desenho que o {@code initDefaultRecipes} dá, com a carne do bicho no lugar
 * das letras E e F.
 */
public final class SewingRecipes {
    public static final List<SewingRecipe> ALL = new ArrayList<>();

    private SewingRecipes() {
    }

    static {
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("cow_torso")), 4, 4,
                Arrays.asList(null, Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), null, Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("heart")), Ingredient.of(MortuorumItems.ORGANS.get("lungs")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BEEF), Ingredient.of(Items.BEEF), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("cow_head")), 4, 3,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("brains")), Ingredient.of(Items.BEEF), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BEEF), Ingredient.of(Items.BEEF), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("cow_arm")), 4, 3,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(Items.BEEF), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("cow_legs")), 4, 4,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BEEF), Ingredient.of(Items.BEEF), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("creeper_torso")), 4, 4,
                Arrays.asList(null, Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), null, Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("heart")), Ingredient.of(MortuorumItems.ORGANS.get("lungs")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.GUNPOWDER), Ingredient.of(Items.GUNPOWDER), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("creeper_legs")), 4, 4,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.GUNPOWDER), Ingredient.of(Items.GUNPOWDER), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("enderman_head")), 4, 3,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("brains")), Ingredient.of(Items.ENDER_PEARL), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.ENDER_PEARL), Ingredient.of(Items.ENDER_PEARL), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("enderman_torso")), 4, 4,
                Arrays.asList(null, Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), null, Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("heart")), Ingredient.of(MortuorumItems.ORGANS.get("lungs")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.ENDER_PEARL), Ingredient.of(Items.ENDER_PEARL), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("enderman_arm")), 4, 3,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(Items.ENDER_PEARL), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("enderman_legs")), 4, 4,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.ENDER_PEARL), Ingredient.of(Items.ENDER_PEARL), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("pig_head")), 4, 3,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("brains")), Ingredient.of(Items.PORKCHOP), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.PORKCHOP), Ingredient.of(Items.PORKCHOP), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("pig_torso")), 4, 4,
                Arrays.asList(null, Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), null, Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("heart")), Ingredient.of(MortuorumItems.ORGANS.get("lungs")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.PORKCHOP), Ingredient.of(Items.PORKCHOP), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("pig_arm")), 4, 3,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(Items.PORKCHOP), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("pig_legs")), 4, 4,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.PORKCHOP), Ingredient.of(Items.PORKCHOP), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("pigzombie_head")), 4, 3,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("brains")), Ingredient.of(Items.ROTTEN_FLESH), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.ROTTEN_FLESH), Ingredient.of(Items.ROTTEN_FLESH), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("pigzombie_torso")), 4, 4,
                Arrays.asList(null, Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), null, Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("heart")), Ingredient.of(MortuorumItems.ORGANS.get("lungs")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.ROTTEN_FLESH), Ingredient.of(Items.ROTTEN_FLESH), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("pigzombie_arm")), 4, 3,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(Items.ROTTEN_FLESH), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("pigzombie_legs")), 4, 4,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.ROTTEN_FLESH), Ingredient.of(Items.ROTTEN_FLESH), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("skeleton_torso")), 4, 4,
                Arrays.asList(null, Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), null, Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("heart")), Ingredient.of(MortuorumItems.ORGANS.get("lungs")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("skeleton_arm")), 4, 3,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(Items.BONE), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("skeleton_legs")), 4, 4,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("spider_head")), 4, 3,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("brains")), Ingredient.of(Items.STRING), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.STRING), Ingredient.of(Items.STRING), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("spider_torso")), 4, 4,
                Arrays.asList(null, Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), null, Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("heart")), Ingredient.of(MortuorumItems.ORGANS.get("lungs")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.STRING), Ingredient.of(Items.STRING), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("spider_legs")), 4, 4,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.STRING), Ingredient.of(Items.STRING), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("zombie_torso")), 4, 4,
                Arrays.asList(null, Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), null, Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("heart")), Ingredient.of(MortuorumItems.ORGANS.get("lungs")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.ROTTEN_FLESH), Ingredient.of(Items.ROTTEN_FLESH), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("zombie_arm")), 4, 3,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(Items.ROTTEN_FLESH), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("zombie_legs")), 4, 4,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.ROTTEN_FLESH), Ingredient.of(Items.ROTTEN_FLESH), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("chicken_head")), 4, 3,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("brains")), Ingredient.of(Items.CHICKEN), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.CHICKEN), Ingredient.of(Items.CHICKEN), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("chicken_torso")), 4, 4,
                Arrays.asList(null, Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), null, Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("heart")), Ingredient.of(MortuorumItems.ORGANS.get("lungs")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.CHICKEN), Ingredient.of(Items.CHICKEN), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("chicken_arm")), 4, 3,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(Items.CHICKEN), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("chicken_legs")), 4, 4,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.CHICKEN), Ingredient.of(Items.CHICKEN), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("villager_head")), 4, 3,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("brains")), Ingredient.of(Items.EMERALD), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.EMERALD), Ingredient.of(Items.EMERALD), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("villager_torso")), 4, 4,
                Arrays.asList(null, Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), null, Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("heart")), Ingredient.of(MortuorumItems.ORGANS.get("lungs")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.EMERALD), Ingredient.of(Items.EMERALD), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("villager_arm")), 4, 3,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(Items.EMERALD), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("villager_legs")), 4, 4,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.EMERALD), Ingredient.of(Items.EMERALD), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("witch_head")), 4, 3,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("brains")), Ingredient.of(Items.GLASS_BOTTLE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.GLASS_BOTTLE), Ingredient.of(Items.GLASS_BOTTLE), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("witch_torso")), 4, 4,
                Arrays.asList(null, Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), null, Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("heart")), Ingredient.of(MortuorumItems.ORGANS.get("lungs")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.GLASS_BOTTLE), Ingredient.of(Items.GLASS_BOTTLE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("witch_arm")), 4, 3,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(Items.GLASS_BOTTLE), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("witch_legs")), 4, 4,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.GLASS_BOTTLE), Ingredient.of(Items.GLASS_BOTTLE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("squid_head")), 4, 3,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("brains")), Ingredient.of(Items.INK_SAC), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.INK_SAC), Ingredient.of(Items.INK_SAC), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("squid_torso")), 4, 4,
                Arrays.asList(null, Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), null, Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("heart")), Ingredient.of(MortuorumItems.ORGANS.get("lungs")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.INK_SAC), Ingredient.of(Items.INK_SAC), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("squid_legs")), 4, 4,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.INK_SAC), Ingredient.of(Items.INK_SAC), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("cave_spider_head")), 4, 3,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("brains")), Ingredient.of(Items.STRING), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.STRING), Ingredient.of(Items.STRING), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("cave_spider_torso")), 4, 4,
                Arrays.asList(null, Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), null, Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("heart")), Ingredient.of(MortuorumItems.ORGANS.get("lungs")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.STRING), Ingredient.of(Items.STRING), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("cave_spider_legs")), 4, 4,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.STRING), Ingredient.of(Items.STRING), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("sheep_head")), 4, 3,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("brains")), Ingredient.of(Items.MUTTON), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.MUTTON), Ingredient.of(Items.MUTTON), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("sheep_torso")), 4, 4,
                Arrays.asList(null, Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), null, Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("heart")), Ingredient.of(MortuorumItems.ORGANS.get("lungs")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.MUTTON), Ingredient.of(Items.MUTTON), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("sheep_arm")), 4, 3,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(Items.MUTTON), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("sheep_legs")), 4, 4,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.MUTTON), Ingredient.of(Items.MUTTON), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("iron_golem_head")), 4, 3,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("brains")), Ingredient.of(Blocks.CARVED_PUMPKIN.asItem()), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Blocks.CARVED_PUMPKIN.asItem()), Ingredient.of(Blocks.CARVED_PUMPKIN.asItem()), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("iron_golem_torso")), 4, 4,
                Arrays.asList(null, Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), null, Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("heart")), Ingredient.of(MortuorumItems.ORGANS.get("lungs")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Blocks.IRON_BLOCK.asItem()), Ingredient.of(Blocks.IRON_BLOCK.asItem()), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("iron_golem_arm")), 4, 3,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(Blocks.IRON_BLOCK.asItem()), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("iron_golem_legs")), 4, 4,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(MortuorumItems.ORGANS.get("muscle")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Blocks.IRON_BLOCK.asItem()), Ingredient.of(Blocks.IRON_BLOCK.asItem()), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.BONE), Ingredient.of(Items.BONE), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));
        ALL.add(SewingRecipe.shaped(new ItemStack(MortuorumItems.PART_ITEMS.get("wolf_head")), 4, 3,
                Arrays.asList(Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("brains")), Ingredient.of(Items.NAME_TAG), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(MortuorumItems.ORGANS.get("skin")), Ingredient.of(Items.NAME_TAG), Ingredient.of(Items.NAME_TAG), Ingredient.of(MortuorumItems.ORGANS.get("skin")))));

        // a pele que sai do couro, sem forma nenhuma
        ALL.add(SewingRecipe.shapeless(new ItemStack(MortuorumItems.ORGANS.get("skin"), 8),
                List.of(Ingredient.of(Items.LEATHER))));
    }
}
