package net.thaumcraft.api.aspects;

/**
 * As anotações de aspecto do {@code ConfigAspects} da 4.2.3.5, na ordem do original.
 *
 * <p><b>Este arquivo é gerado</b> pelo {@code scratchpad/aspectos-jar.js} a partir do jar descompilado — não da
 * fonte legível do GitHub, que inventava uma tabela inteira para as coisas do jogo. O dicionário de minérios de
 * então virou as marcas de convenção de hoje ({@code c:ores/iron}, {@code c:dyes}…), e os metadados viraram os
 * itens de hoje (as dezesseis lãs, as pedras, os peixes…). O que não está aqui é deduzido das receitas.
 */
final class ConfigAspectsTable {
    private ConfigAspectsTable() {
    }

    static void register(ObjectAspects.Registrar r) {
        r.item("minecraft:stone", new AspectList().add(Aspects.EARTH, 2));
        r.item("minecraft:cobblestone", new AspectList().add(Aspects.EARTH, 1).add(Aspects.ENTROPY, 1));
        r.tag("minecraft:logs", new AspectList().add(Aspects.TREE, 4));
        r.tag("minecraft:planks", new AspectList().add(Aspects.TREE, 1));
        r.tag("minecraft:wooden_slabs", new AspectList().add(Aspects.TREE, 1));
        r.tag("minecraft:wooden_stairs", new AspectList().add(Aspects.TREE, 1));
        r.item("minecraft:stick", new AspectList().add(Aspects.TREE, 1));
        r.tag("minecraft:saplings", new AspectList().add(Aspects.TREE, 1).add(Aspects.PLANT, 2));
        r.tag("minecraft:leaves", new AspectList().add(Aspects.PLANT, 1));
        r.tag("c:dyes", new AspectList().add(Aspects.SENSES, 1));
        r.item("minecraft:ink_sac", new AspectList().add(Aspects.SENSES, 1));
        r.item("minecraft:cocoa_beans", new AspectList().add(Aspects.SENSES, 1));
        r.item("minecraft:lapis_lazuli", new AspectList().add(Aspects.SENSES, 1));
        r.item("minecraft:bone_meal", new AspectList().add(Aspects.SENSES, 1));
        r.tag("c:ores/lapis", new AspectList().add(Aspects.EARTH, 1).add(Aspects.SENSES, 3));
        r.tag("c:ores/diamond", new AspectList().add(Aspects.EARTH, 1).add(Aspects.GREED, 3).add(Aspects.CRYSTAL, 3));
        r.tag("c:gems/diamond", new AspectList().add(Aspects.CRYSTAL, 4).add(Aspects.GREED, 4));
        r.tag("c:ores/redstone", new AspectList().add(Aspects.EARTH, 1).add(Aspects.ENERGY, 2).add(Aspects.MECHANISM, 2));
        r.item("minecraft:redstone_ore", new AspectList().add(Aspects.EARTH, 1).add(Aspects.ENERGY, 3).add(Aspects.MECHANISM, 2));
        r.tag("c:ores/emerald", new AspectList().add(Aspects.EARTH, 1).add(Aspects.GREED, 4).add(Aspects.CRYSTAL, 3));
        r.tag("c:gems/emerald", new AspectList().add(Aspects.CRYSTAL, 4).add(Aspects.GREED, 5));
        r.tag("c:ores/quartz", new AspectList().add(Aspects.EARTH, 1).add(Aspects.CRYSTAL, 3));
        r.item("minecraft:quartz", new AspectList().add(Aspects.CRYSTAL, 1).add(Aspects.ENERGY, 1));
        r.item("minecraft:gold_nugget", new AspectList().add(Aspects.METAL, 1));
        r.tag("c:nuggets/iron", new AspectList().add(Aspects.METAL, 1));
        r.tag("c:ores/iron", new AspectList().add(Aspects.EARTH, 1).add(Aspects.METAL, 3));
        r.tag("c:dusts/iron", new AspectList().add(Aspects.METAL, 3).add(Aspects.ENTROPY, 1));
        r.item("minecraft:iron_ingot", new AspectList().add(Aspects.METAL, 4));
        r.tag("c:ores/gold", new AspectList().add(Aspects.EARTH, 1).add(Aspects.METAL, 2).add(Aspects.GREED, 1));
        r.tag("c:dusts/gold", new AspectList().add(Aspects.METAL, 2).add(Aspects.ENTROPY, 1).add(Aspects.GREED, 1));
        r.item("minecraft:gold_ingot", new AspectList().add(Aspects.METAL, 3).add(Aspects.GREED, 2));
        r.item("minecraft:coal_ore", new AspectList().add(Aspects.EARTH, 1).add(Aspects.ENERGY, 2).add(Aspects.FIRE, 1));
        r.item("minecraft:coal", new AspectList().add(Aspects.ENERGY, 2).add(Aspects.FIRE, 2));
        r.item("minecraft:charcoal", new AspectList().add(Aspects.ENERGY, 2).add(Aspects.FIRE, 2));
        r.tag("c:dusts/redstone", new AspectList().add(Aspects.ENERGY, 2).add(Aspects.MECHANISM, 1));
        r.tag("c:dusts/glowstone", new AspectList().add(Aspects.SENSES, 1).add(Aspects.LIGHT, 2));
        r.item("minecraft:glowstone", new AspectList().add(Aspects.SENSES, 3).add(Aspects.LIGHT, 10));
        r.tag("c:nuggets/copper", new AspectList().add(Aspects.METAL, 1));
        r.tag("c:ingots/copper", new AspectList().add(Aspects.METAL, 3).add(Aspects.EXCHANGE, 1));
        r.tag("c:dusts/copper", new AspectList().add(Aspects.METAL, 2).add(Aspects.ENTROPY, 1).add(Aspects.EXCHANGE, 1));
        r.tag("c:ores/copper", new AspectList().add(Aspects.METAL, 2).add(Aspects.EARTH, 1).add(Aspects.EXCHANGE, 1));
        r.item("thaumcraft:native_copper_cluster", new AspectList().add(Aspects.ORDER, 1).add(Aspects.METAL, 5).add(Aspects.EARTH, 1).add(Aspects.EXCHANGE, 2));
        r.tag("c:nuggets/tin", new AspectList().add(Aspects.METAL, 1));
        r.tag("c:ingots/tin", new AspectList().add(Aspects.METAL, 3).add(Aspects.CRYSTAL, 1));
        r.tag("c:dusts/tin", new AspectList().add(Aspects.METAL, 2).add(Aspects.ENTROPY, 1).add(Aspects.CRYSTAL, 1));
        r.tag("c:ores/tin", new AspectList().add(Aspects.METAL, 3).add(Aspects.ENTROPY, 1).add(Aspects.CRYSTAL, 1));
        r.tag("c:nuggets/silver", new AspectList().add(Aspects.METAL, 1));
        r.tag("c:ingots/silver", new AspectList().add(Aspects.METAL, 3).add(Aspects.GREED, 1));
        r.tag("c:dusts/silver", new AspectList().add(Aspects.METAL, 2).add(Aspects.ENTROPY, 1).add(Aspects.GREED, 1));
        r.tag("c:ores/silver", new AspectList().add(Aspects.METAL, 3).add(Aspects.ENTROPY, 1).add(Aspects.GREED, 1));
        r.tag("c:nuggets/lead", new AspectList().add(Aspects.METAL, 1));
        r.tag("c:ingots/lead", new AspectList().add(Aspects.METAL, 3).add(Aspects.ORDER, 1));
        r.tag("c:dusts/lead", new AspectList().add(Aspects.METAL, 2).add(Aspects.ENTROPY, 1).add(Aspects.ORDER, 1));
        r.tag("c:ores/lead", new AspectList().add(Aspects.METAL, 3).add(Aspects.ENTROPY, 1).add(Aspects.ORDER, 1));
        r.item("minecraft:bedrock", new AspectList().add(Aspects.VOID, 16).add(Aspects.ENTROPY, 16).add(Aspects.EARTH, 16).add(Aspects.DARKNESS, 16));
        r.item("minecraft:dirt", new AspectList().add(Aspects.EARTH, 2));
        r.item("minecraft:coarse_dirt", new AspectList().add(Aspects.EARTH, 2));
        r.item("minecraft:podzol", new AspectList().add(Aspects.EARTH, 2));
        r.item("minecraft:podzol", new AspectList().add(Aspects.EARTH, 1).add(Aspects.PLANT, 1));
        r.item("minecraft:farmland", new AspectList().add(Aspects.EARTH, 1).add(Aspects.HARVEST, 2));
        r.item("minecraft:sand", new AspectList().add(Aspects.EARTH, 1).add(Aspects.ENTROPY, 1));
        r.item("minecraft:red_sand", new AspectList().add(Aspects.EARTH, 1).add(Aspects.ENTROPY, 1));
        r.item("minecraft:grass_block", new AspectList().add(Aspects.EARTH, 1).add(Aspects.PLANT, 1));
        r.item("minecraft:clay_ball", new AspectList().add(Aspects.WATER, 1).add(Aspects.EARTH, 1));
        r.item("minecraft:end_stone", new AspectList().add(Aspects.EARTH, 1).add(Aspects.DARKNESS, 1));
        r.item("minecraft:gravel", new AspectList().add(Aspects.EARTH, 1).add(Aspects.EARTH, 1));
        r.item("minecraft:mycelium", new AspectList().add(Aspects.EARTH, 1).add(Aspects.PLANT, 1));
        r.item("minecraft:clay", new AspectList().add(Aspects.EARTH, 3).add(Aspects.WATER, 3));
        r.item("minecraft:terracotta", new AspectList().add(Aspects.EARTH, 4).add(Aspects.FIRE, 1));
        r.item("minecraft:white_terracotta", new AspectList().add(Aspects.EARTH, 3).add(Aspects.FIRE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:orange_terracotta", new AspectList().add(Aspects.EARTH, 3).add(Aspects.FIRE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:magenta_terracotta", new AspectList().add(Aspects.EARTH, 3).add(Aspects.FIRE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:light_blue_terracotta", new AspectList().add(Aspects.EARTH, 3).add(Aspects.FIRE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:yellow_terracotta", new AspectList().add(Aspects.EARTH, 3).add(Aspects.FIRE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:lime_terracotta", new AspectList().add(Aspects.EARTH, 3).add(Aspects.FIRE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:pink_terracotta", new AspectList().add(Aspects.EARTH, 3).add(Aspects.FIRE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:gray_terracotta", new AspectList().add(Aspects.EARTH, 3).add(Aspects.FIRE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:light_gray_terracotta", new AspectList().add(Aspects.EARTH, 3).add(Aspects.FIRE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:cyan_terracotta", new AspectList().add(Aspects.EARTH, 3).add(Aspects.FIRE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:purple_terracotta", new AspectList().add(Aspects.EARTH, 3).add(Aspects.FIRE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:blue_terracotta", new AspectList().add(Aspects.EARTH, 3).add(Aspects.FIRE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:brown_terracotta", new AspectList().add(Aspects.EARTH, 3).add(Aspects.FIRE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:green_terracotta", new AspectList().add(Aspects.EARTH, 3).add(Aspects.FIRE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:red_terracotta", new AspectList().add(Aspects.EARTH, 3).add(Aspects.FIRE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:black_terracotta", new AspectList().add(Aspects.EARTH, 3).add(Aspects.FIRE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:brick", new AspectList().add(Aspects.EARTH, 1).add(Aspects.FIRE, 1));
        r.item("minecraft:nether_brick", new AspectList().add(Aspects.FIRE, 1));
        r.item("minecraft:soul_sand", new AspectList().add(Aspects.EARTH, 1).add(Aspects.TRAP, 1).add(Aspects.SOUL, 1));
        r.item("minecraft:netherrack", new AspectList().add(Aspects.EARTH, 1).add(Aspects.EARTH, 1).add(Aspects.FIRE, 1));
        r.item("minecraft:nether_bricks", new AspectList().add(Aspects.EARTH, 2).add(Aspects.FIRE, 1));
        r.item("minecraft:glass", new AspectList().add(Aspects.CRYSTAL, 1));
        r.item("minecraft:white_stained_glass", new AspectList().add(Aspects.CRYSTAL, 1));
        r.item("minecraft:orange_stained_glass", new AspectList().add(Aspects.CRYSTAL, 1));
        r.item("minecraft:magenta_stained_glass", new AspectList().add(Aspects.CRYSTAL, 1));
        r.item("minecraft:light_blue_stained_glass", new AspectList().add(Aspects.CRYSTAL, 1));
        r.item("minecraft:yellow_stained_glass", new AspectList().add(Aspects.CRYSTAL, 1));
        r.item("minecraft:lime_stained_glass", new AspectList().add(Aspects.CRYSTAL, 1));
        r.item("minecraft:pink_stained_glass", new AspectList().add(Aspects.CRYSTAL, 1));
        r.item("minecraft:gray_stained_glass", new AspectList().add(Aspects.CRYSTAL, 1));
        r.item("minecraft:light_gray_stained_glass", new AspectList().add(Aspects.CRYSTAL, 1));
        r.item("minecraft:cyan_stained_glass", new AspectList().add(Aspects.CRYSTAL, 1));
        r.item("minecraft:purple_stained_glass", new AspectList().add(Aspects.CRYSTAL, 1));
        r.item("minecraft:blue_stained_glass", new AspectList().add(Aspects.CRYSTAL, 1));
        r.item("minecraft:brown_stained_glass", new AspectList().add(Aspects.CRYSTAL, 1));
        r.item("minecraft:green_stained_glass", new AspectList().add(Aspects.CRYSTAL, 1));
        r.item("minecraft:red_stained_glass", new AspectList().add(Aspects.CRYSTAL, 1));
        r.item("minecraft:black_stained_glass", new AspectList().add(Aspects.CRYSTAL, 1));
        r.item("minecraft:mossy_cobblestone", new AspectList().add(Aspects.EARTH, 1).add(Aspects.PLANT, 1).add(Aspects.MAGIC, 1));
        r.item("minecraft:obsidian", new AspectList().add(Aspects.EARTH, 2).add(Aspects.FIRE, 2).add(Aspects.DARKNESS, 1));
        r.item("minecraft:infested_stone", new AspectList().add(Aspects.EARTH, 2).add(Aspects.BEAST, 1).add(Aspects.TRAP, 1));
        r.item("minecraft:infested_cobblestone", new AspectList().add(Aspects.EARTH, 2).add(Aspects.BEAST, 1).add(Aspects.TRAP, 1));
        r.item("minecraft:infested_stone_bricks", new AspectList().add(Aspects.EARTH, 2).add(Aspects.BEAST, 1).add(Aspects.TRAP, 1));
        r.item("minecraft:infested_mossy_stone_bricks", new AspectList().add(Aspects.EARTH, 2).add(Aspects.BEAST, 1).add(Aspects.TRAP, 1));
        r.item("minecraft:infested_cracked_stone_bricks", new AspectList().add(Aspects.EARTH, 2).add(Aspects.BEAST, 1).add(Aspects.TRAP, 1));
        r.item("minecraft:infested_chiseled_stone_bricks", new AspectList().add(Aspects.EARTH, 2).add(Aspects.BEAST, 1).add(Aspects.TRAP, 1));
        r.item("minecraft:stone_bricks", new AspectList().add(Aspects.EARTH, 2));
        r.item("minecraft:mossy_stone_bricks", new AspectList().add(Aspects.EARTH, 2));
        r.item("minecraft:cracked_stone_bricks", new AspectList().add(Aspects.EARTH, 2));
        r.item("minecraft:chiseled_stone_bricks", new AspectList().add(Aspects.EARTH, 2));
        r.item("minecraft:mossy_stone_bricks", minus(r.copy("minecraft:stone_bricks"), Aspects.EARTH, 1).add(Aspects.PLANT, 1));
        r.item("minecraft:cracked_stone_bricks", minus(r.copy("minecraft:stone_bricks"), Aspects.EARTH, 1).add(Aspects.ENTROPY, 1));
        r.item("minecraft:chiseled_stone_bricks", minus(r.copy("minecraft:stone_bricks"), Aspects.EARTH, 1).add(Aspects.ORDER, 1));
        r.complex("minecraft:sandstone", minus(new AspectList().add(Aspects.EARTH, 1), Aspects.EARTH, 1));
        r.complex("minecraft:chiseled_sandstone", minus(new AspectList().add(Aspects.EARTH, 1), Aspects.EARTH, 1));
        r.complex("minecraft:cut_sandstone", minus(new AspectList().add(Aspects.EARTH, 1), Aspects.EARTH, 1));
        r.item("minecraft:chiseled_sandstone", minus(r.copy("minecraft:sandstone"), Aspects.EARTH, 1).add(Aspects.MAGIC, 1));
        r.item("minecraft:cut_sandstone", minus(r.copy("minecraft:sandstone"), Aspects.EARTH, 1).add(Aspects.ORDER, 1));
        r.item("minecraft:short_grass", new AspectList().add(Aspects.PLANT, 1).add(Aspects.AIR, 1));
        r.item("minecraft:fern", new AspectList().add(Aspects.PLANT, 1).add(Aspects.AIR, 1));
        r.item("minecraft:sunflower", new AspectList().add(Aspects.PLANT, 1).add(Aspects.AIR, 1));
        r.item("minecraft:lilac", new AspectList().add(Aspects.PLANT, 1).add(Aspects.AIR, 1));
        r.item("minecraft:tall_grass", new AspectList().add(Aspects.PLANT, 1).add(Aspects.AIR, 1));
        r.item("minecraft:large_fern", new AspectList().add(Aspects.PLANT, 1).add(Aspects.AIR, 1));
        r.item("minecraft:rose_bush", new AspectList().add(Aspects.PLANT, 1).add(Aspects.AIR, 1));
        r.item("minecraft:peony", new AspectList().add(Aspects.PLANT, 1).add(Aspects.AIR, 1));
        r.item("minecraft:lily_pad", new AspectList().add(Aspects.PLANT, 2).add(Aspects.WATER, 1));
        r.item("minecraft:dead_bush", new AspectList().add(Aspects.PLANT, 1).add(Aspects.ENTROPY, 1));
        r.item("minecraft:vine", new AspectList().add(Aspects.PLANT, 1));
        r.item("minecraft:wheat_seeds", new AspectList().add(Aspects.PLANT, 1));
        r.item("minecraft:melon_seeds", new AspectList().add(Aspects.PLANT, 1));
        r.item("minecraft:pumpkin_seeds", new AspectList().add(Aspects.PLANT, 1));
        r.item("minecraft:melon_slice", new AspectList().add(Aspects.HUNGER, 1));
        r.item("minecraft:nether_wart", new AspectList().add(Aspects.PLANT, 1).add(Aspects.MAGIC, 1));
        r.item("minecraft:poppy", new AspectList().add(Aspects.PLANT, 1).add(Aspects.LIFE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:blue_orchid", new AspectList().add(Aspects.PLANT, 1).add(Aspects.LIFE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:allium", new AspectList().add(Aspects.PLANT, 1).add(Aspects.LIFE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:azure_bluet", new AspectList().add(Aspects.PLANT, 1).add(Aspects.LIFE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:red_tulip", new AspectList().add(Aspects.PLANT, 1).add(Aspects.LIFE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:orange_tulip", new AspectList().add(Aspects.PLANT, 1).add(Aspects.LIFE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:white_tulip", new AspectList().add(Aspects.PLANT, 1).add(Aspects.LIFE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:pink_tulip", new AspectList().add(Aspects.PLANT, 1).add(Aspects.LIFE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:oxeye_daisy", new AspectList().add(Aspects.PLANT, 1).add(Aspects.LIFE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:dandelion", new AspectList().add(Aspects.PLANT, 1).add(Aspects.LIFE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:cactus", new AspectList().add(Aspects.PLANT, 3).add(Aspects.WATER, 1).add(Aspects.ENTROPY, 1));
        r.item("minecraft:brown_mushroom", new AspectList().add(Aspects.PLANT, 1).add(Aspects.DARKNESS, 1).add(Aspects.EARTH, 1));
        r.item("minecraft:red_mushroom", new AspectList().add(Aspects.PLANT, 1).add(Aspects.DARKNESS, 1).add(Aspects.FIRE, 1));
        r.item("minecraft:brown_mushroom_block", new AspectList().add(Aspects.PLANT, 2).add(Aspects.DARKNESS, 1).add(Aspects.EARTH, 1));
        r.item("minecraft:mushroom_stem", new AspectList().add(Aspects.PLANT, 2).add(Aspects.DARKNESS, 1).add(Aspects.EARTH, 1));
        r.item("minecraft:red_mushroom_block", new AspectList().add(Aspects.PLANT, 2).add(Aspects.DARKNESS, 1).add(Aspects.FIRE, 1));
        r.item("minecraft:sugar_cane", new AspectList().add(Aspects.PLANT, 1).add(Aspects.WATER, 1).add(Aspects.AIR, 1));
        r.item("minecraft:wheat", new AspectList().add(Aspects.CROP, 2).add(Aspects.HUNGER, 1));
        r.item("minecraft:apple", new AspectList().add(Aspects.CROP, 2).add(Aspects.HUNGER, 1));
        r.item("minecraft:carrot", new AspectList().add(Aspects.CROP, 1).add(Aspects.HUNGER, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:potato", new AspectList().add(Aspects.CROP, 1).add(Aspects.HUNGER, 1).add(Aspects.EARTH, 1));
        r.item("minecraft:baked_potato", new AspectList().add(Aspects.CROP, 1).add(Aspects.HUNGER, 2));
        r.item("minecraft:poisonous_potato", new AspectList().add(Aspects.CROP, 1).add(Aspects.POISON, 2));
        r.item("minecraft:pumpkin", new AspectList().add(Aspects.CROP, 2));
        r.item("minecraft:carved_pumpkin", new AspectList().add(Aspects.CROP, 2));
        r.complex("minecraft:melon", minus(new AspectList().add(Aspects.CROP, 2), Aspects.HUNGER, 4));
        r.item("minecraft:name_tag", new AspectList().add(Aspects.MIND, 2).add(Aspects.BEAST, 2));
        r.item("minecraft:iron_horse_armor", new AspectList().add(Aspects.ARMOR, 2).add(Aspects.BEAST, 2));
        r.item("minecraft:golden_horse_armor", new AspectList().add(Aspects.ARMOR, 4).add(Aspects.BEAST, 2));
        r.item("minecraft:diamond_horse_armor", new AspectList().add(Aspects.ARMOR, 6).add(Aspects.BEAST, 2));
        r.item("minecraft:ice", new AspectList().add(Aspects.COLD, 4));
        r.item("minecraft:packed_ice", new AspectList().add(Aspects.COLD, 3).add(Aspects.EARTH, 1));
        r.item("minecraft:snowball", new AspectList().add(Aspects.COLD, 1));
        r.item("minecraft:cookie", new AspectList().add(Aspects.HUNGER, 1));
        r.item("minecraft:potion", new AspectList().add(Aspects.WATER, 1).add(Aspects.CRYSTAL, 1));
        r.item("minecraft:torch", new AspectList().add(Aspects.LIGHT, 1));
        r.item("minecraft:cobweb", new AspectList().add(Aspects.TRAP, 2).add(Aspects.CLOTH, 1));
        r.item("minecraft:flint", new AspectList().add(Aspects.EARTH, 1).add(Aspects.TOOL, 1));
        r.item("minecraft:string", new AspectList().add(Aspects.BEAST, 1).add(Aspects.CLOTH, 1));
        r.item("minecraft:slime_ball", new AspectList().add(Aspects.SLIME, 2));
        r.item("minecraft:leather", new AspectList().add(Aspects.CLOTH, 2).add(Aspects.BEAST, 1).add(Aspects.ARMOR, 1));
        r.item("minecraft:rotten_flesh", new AspectList().add(Aspects.MAN, 1).add(Aspects.FLESH, 2));
        r.item("minecraft:feather", new AspectList().add(Aspects.FLIGHT, 2).add(Aspects.AIR, 1));
        r.item("minecraft:bone", new AspectList().add(Aspects.DEATH, 2).add(Aspects.FLESH, 1));
        r.item("minecraft:egg", new AspectList().add(Aspects.SLIME, 1).add(Aspects.LIFE, 1).add(Aspects.BEAST, 1));
        r.item("minecraft:spider_eye", new AspectList().add(Aspects.SENSES, 2).add(Aspects.BEAST, 2).add(Aspects.POISON, 2));
        r.item("minecraft:gunpowder", new AspectList().add(Aspects.FIRE, 4).add(Aspects.ENTROPY, 4));
        r.item("minecraft:white_wool", new AspectList().add(Aspects.CLOTH, 4).add(Aspects.CRAFT, 1));
        r.item("minecraft:orange_wool", new AspectList().add(Aspects.CLOTH, 4).add(Aspects.CRAFT, 1));
        r.item("minecraft:magenta_wool", new AspectList().add(Aspects.CLOTH, 4).add(Aspects.CRAFT, 1));
        r.item("minecraft:light_blue_wool", new AspectList().add(Aspects.CLOTH, 4).add(Aspects.CRAFT, 1));
        r.item("minecraft:yellow_wool", new AspectList().add(Aspects.CLOTH, 4).add(Aspects.CRAFT, 1));
        r.item("minecraft:lime_wool", new AspectList().add(Aspects.CLOTH, 4).add(Aspects.CRAFT, 1));
        r.item("minecraft:pink_wool", new AspectList().add(Aspects.CLOTH, 4).add(Aspects.CRAFT, 1));
        r.item("minecraft:gray_wool", new AspectList().add(Aspects.CLOTH, 4).add(Aspects.CRAFT, 1));
        r.item("minecraft:light_gray_wool", new AspectList().add(Aspects.CLOTH, 4).add(Aspects.CRAFT, 1));
        r.item("minecraft:cyan_wool", new AspectList().add(Aspects.CLOTH, 4).add(Aspects.CRAFT, 1));
        r.item("minecraft:purple_wool", new AspectList().add(Aspects.CLOTH, 4).add(Aspects.CRAFT, 1));
        r.item("minecraft:blue_wool", new AspectList().add(Aspects.CLOTH, 4).add(Aspects.CRAFT, 1));
        r.item("minecraft:brown_wool", new AspectList().add(Aspects.CLOTH, 4).add(Aspects.CRAFT, 1));
        r.item("minecraft:green_wool", new AspectList().add(Aspects.CLOTH, 4).add(Aspects.CRAFT, 1));
        r.item("minecraft:red_wool", new AspectList().add(Aspects.CLOTH, 4).add(Aspects.CRAFT, 1));
        r.item("minecraft:black_wool", new AspectList().add(Aspects.CLOTH, 4).add(Aspects.CRAFT, 1));
        r.item("minecraft:cod", new AspectList().add(Aspects.FLESH, 3).add(Aspects.LIFE, 1).add(Aspects.WATER, 1));
        r.item("minecraft:salmon", new AspectList().add(Aspects.FLESH, 3).add(Aspects.LIFE, 1).add(Aspects.WATER, 1));
        r.item("minecraft:tropical_fish", new AspectList().add(Aspects.FLESH, 3).add(Aspects.LIFE, 1).add(Aspects.WATER, 1));
        r.item("minecraft:pufferfish", new AspectList().add(Aspects.FLESH, 3).add(Aspects.LIFE, 1).add(Aspects.WATER, 1));
        r.item("minecraft:cooked_cod", new AspectList().add(Aspects.CRAFT, 1).add(Aspects.FLESH, 4).add(Aspects.HUNGER, 3));
        r.item("minecraft:cooked_salmon", new AspectList().add(Aspects.CRAFT, 1).add(Aspects.FLESH, 4).add(Aspects.HUNGER, 3));
        r.item("minecraft:chicken", new AspectList().add(Aspects.FLESH, 3).add(Aspects.LIFE, 2).add(Aspects.BEAST, 1));
        r.item("minecraft:cooked_chicken", new AspectList().add(Aspects.CRAFT, 1).add(Aspects.FLESH, 4).add(Aspects.HUNGER, 3));
        r.item("minecraft:porkchop", new AspectList().add(Aspects.FLESH, 3).add(Aspects.LIFE, 1).add(Aspects.BEAST, 1));
        r.item("minecraft:cooked_porkchop", new AspectList().add(Aspects.CRAFT, 1).add(Aspects.FLESH, 3).add(Aspects.HUNGER, 3));
        r.item("minecraft:beef", new AspectList().add(Aspects.FLESH, 4).add(Aspects.LIFE, 2).add(Aspects.BEAST, 1));
        r.item("minecraft:cooked_beef", new AspectList().add(Aspects.CRAFT, 1).add(Aspects.FLESH, 4).add(Aspects.HUNGER, 4));
        r.item("minecraft:blaze_rod", new AspectList().add(Aspects.FIRE, 4).add(Aspects.MAGIC, 2));
        r.item("minecraft:saddle", new AspectList().add(Aspects.BEAST, 2).add(Aspects.CLOTH, 3).add(Aspects.TRAVEL, 3));
        r.item("minecraft:ender_pearl", new AspectList().add(Aspects.ELDRITCH, 4).add(Aspects.MAGIC, 2).add(Aspects.TRAVEL, 4));
        r.item("minecraft:ghast_tear", new AspectList().add(Aspects.WATER, 1).add(Aspects.UNDEAD, 4).add(Aspects.SOUL, 4));
        r.item("minecraft:skeleton_skull", new AspectList().add(Aspects.DEATH, 4).add(Aspects.SOUL, 4).add(Aspects.UNDEAD, 4));
        r.item("minecraft:wither_skeleton_skull", new AspectList().add(Aspects.DEATH, 4).add(Aspects.SOUL, 4).add(Aspects.UNDEAD, 4).add(Aspects.POISON, 4));
        r.item("minecraft:zombie_head", new AspectList().add(Aspects.DEATH, 4).add(Aspects.SOUL, 4).add(Aspects.FLESH, 4));
        r.item("minecraft:player_head", new AspectList().add(Aspects.DEATH, 4).add(Aspects.SOUL, 4).add(Aspects.MAN, 4));
        r.item("minecraft:creeper_head", new AspectList().add(Aspects.DEATH, 4).add(Aspects.SOUL, 4).add(Aspects.ENTROPY, 2).add(Aspects.FIRE, 2));
        r.item("minecraft:music_disc_11", new AspectList().add(Aspects.SENSES, 4).add(Aspects.AIR, 4).add(Aspects.GREED, 4));
        r.item("minecraft:music_disc_13", new AspectList().add(Aspects.SENSES, 4).add(Aspects.AIR, 4).add(Aspects.WATER, 4).add(Aspects.GREED, 4));
        r.item("minecraft:music_disc_cat", new AspectList().add(Aspects.SENSES, 4).add(Aspects.AIR, 4).add(Aspects.BEAST, 4).add(Aspects.GREED, 4));
        r.item("minecraft:music_disc_chirp", new AspectList().add(Aspects.SENSES, 4).add(Aspects.AIR, 4).add(Aspects.EARTH, 4).add(Aspects.GREED, 4));
        r.item("minecraft:music_disc_far", new AspectList().add(Aspects.SENSES, 4).add(Aspects.AIR, 4).add(Aspects.ELDRITCH, 4).add(Aspects.GREED, 4));
        r.item("minecraft:music_disc_mall", new AspectList().add(Aspects.SENSES, 4).add(Aspects.AIR, 4).add(Aspects.MAN, 4).add(Aspects.GREED, 4));
        r.item("minecraft:music_disc_mellohi", new AspectList().add(Aspects.SENSES, 4).add(Aspects.AIR, 4).add(Aspects.CRAFT, 4).add(Aspects.GREED, 4));
        r.item("minecraft:music_disc_stal", new AspectList().add(Aspects.SENSES, 4).add(Aspects.AIR, 4).add(Aspects.DARKNESS, 4).add(Aspects.GREED, 4));
        r.item("minecraft:music_disc_strad", new AspectList().add(Aspects.SENSES, 4).add(Aspects.AIR, 4).add(Aspects.MECHANISM, 4).add(Aspects.GREED, 4));
        r.item("minecraft:music_disc_ward", new AspectList().add(Aspects.SENSES, 4).add(Aspects.AIR, 4).add(Aspects.MAGIC, 4).add(Aspects.GREED, 4));
        r.item("minecraft:music_disc_blocks", new AspectList().add(Aspects.SENSES, 4).add(Aspects.AIR, 4).add(Aspects.TOOL, 4).add(Aspects.GREED, 4));
        r.item("minecraft:music_disc_wait", new AspectList().add(Aspects.SENSES, 4).add(Aspects.AIR, 4).add(Aspects.TRAP, 4).add(Aspects.GREED, 4));
        r.item("minecraft:nether_star", new AspectList().add(Aspects.ELDRITCH, 8).add(Aspects.MAGIC, 8).add(Aspects.ORDER, 8).add(Aspects.LIGHT, 8));
        r.item("minecraft:chainmail_helmet", new AspectList().add(Aspects.METAL, 8));
        r.item("minecraft:chainmail_chestplate", new AspectList().add(Aspects.METAL, 12));
        r.item("minecraft:chainmail_leggings", new AspectList().add(Aspects.METAL, 11));
        r.item("minecraft:chainmail_boots", new AspectList().add(Aspects.METAL, 7));
        r.complex("minecraft:paper", new AspectList().add(Aspects.MIND, 1));
        r.complex("minecraft:book", new AspectList().add(Aspects.MIND, 3));
        r.complex("minecraft:enchanted_book", r.copy("minecraft:book"));
        r.complex("minecraft:bookshelf", new AspectList().add(Aspects.MIND, 8));
        r.item("minecraft:dragon_egg", new AspectList().add(Aspects.ELDRITCH, 8).add(Aspects.BEAST, 8).add(Aspects.MAGIC, 8));
        r.item("minecraft:end_portal_frame", new AspectList().add(Aspects.ELDRITCH, 4).add(Aspects.MECHANISM, 4).add(Aspects.TRAVEL, 4));
        r.item("minecraft:spawner", new AspectList().add(Aspects.BEAST, 4).add(Aspects.TRAVEL, 4).add(Aspects.UNDEAD, 4).add(Aspects.MAGIC, 4));
        r.complex("minecraft:ender_eye", new AspectList().add(Aspects.SENSES, 4));
        r.complex("minecraft:arrow", new AspectList().add(Aspects.WEAPON, 1));
        r.complex("minecraft:glass_bottle", new AspectList().add(Aspects.VOID, 1));
        r.complex("minecraft:chest", new AspectList().add(Aspects.VOID, 4));
        r.complex("minecraft:golden_apple", new AspectList().add(Aspects.MAGIC, 2).add(Aspects.HEAL, 4));
        r.complex("minecraft:enchanted_golden_apple", new AspectList().add(Aspects.MAGIC, 4).add(Aspects.HEAL, 8));
        r.complex("minecraft:bowl", new AspectList().add(Aspects.VOID, 1));
        r.complex("minecraft:mushroom_stew", new AspectList().add(Aspects.HUNGER, 4));
        r.complex("minecraft:minecart", new AspectList().add(Aspects.MECHANISM, 2).add(Aspects.TRAVEL, 4));
        r.complex("minecraft:iron_door", new AspectList().add(Aspects.MECHANISM, 2).add(Aspects.MOTION, 1));
        r.complex("minecraft:oak_door", new AspectList().add(Aspects.MECHANISM, 1).add(Aspects.MOTION, 1));
        r.complex("minecraft:oak_boat", new AspectList().add(Aspects.WATER, 4).add(Aspects.TRAVEL, 4));
        r.complex("minecraft:flint_and_steel", new AspectList().add(Aspects.FIRE, 4));
        r.complex("minecraft:fishing_rod", new AspectList().add(Aspects.WATER, 1).add(Aspects.TOOL, 1));
        r.item("minecraft:bucket", new AspectList().add(Aspects.METAL, 8).add(Aspects.VOID, 1));
        r.item("minecraft:water_bucket", r.copy("minecraft:bucket").add(Aspects.WATER, 4));
        r.item("minecraft:lava_bucket", r.copy("minecraft:bucket").add(Aspects.FIRE, 4).add(Aspects.EARTH, 1));
        r.item("minecraft:milk_bucket", r.copy("minecraft:bucket").add(Aspects.HUNGER, 2).add(Aspects.HEAL, 2).add(Aspects.WATER, 2));
        r.complex("minecraft:brewing_stand", new AspectList().add(Aspects.CRAFT, 2).add(Aspects.WATER, 2));
        r.complex("minecraft:stone_button", new AspectList().add(Aspects.MECHANISM, 1));
        r.complex("minecraft:rail", new AspectList().add(Aspects.METAL, 1).add(Aspects.TRAVEL, 1));
        r.complex("minecraft:detector_rail", new AspectList().add(Aspects.MECHANISM, 1).add(Aspects.SENSES, 1));
        r.complex("minecraft:powered_rail", new AspectList().add(Aspects.MECHANISM, 1).add(Aspects.ENERGY, 1));
        r.complex("minecraft:activator_rail", new AspectList().add(Aspects.MECHANISM, 2));
        r.complex("minecraft:oak_fence_gate", new AspectList().add(Aspects.MECHANISM, 1).add(Aspects.TRAVEL, 1));
        r.complex("minecraft:oak_pressure_plate", new AspectList().add(Aspects.MECHANISM, 1).add(Aspects.SENSES, 1));
        r.complex("minecraft:stone_pressure_plate", new AspectList().add(Aspects.MECHANISM, 1).add(Aspects.SENSES, 1));
        r.complex("minecraft:light_weighted_pressure_plate", new AspectList().add(Aspects.MECHANISM, 1).add(Aspects.SENSES, 1));
        r.complex("minecraft:heavy_weighted_pressure_plate", new AspectList().add(Aspects.MECHANISM, 1).add(Aspects.SENSES, 1));
        r.complex("minecraft:lever", new AspectList().add(Aspects.MECHANISM, 1));
        r.complex("minecraft:redstone_torch", new AspectList().add(Aspects.MECHANISM, 2));
        r.complex("minecraft:piston", new AspectList().add(Aspects.MECHANISM, 2).add(Aspects.MOTION, 4));
        r.complex("minecraft:sticky_piston", new AspectList().add(Aspects.MECHANISM, 2).add(Aspects.MOTION, 4));
        r.complex("minecraft:jukebox", new AspectList().add(Aspects.SENSES, 4).add(Aspects.MECHANISM, 2).add(Aspects.AIR, 4));
        r.complex("minecraft:note_block", new AspectList().add(Aspects.SENSES, 4).add(Aspects.MECHANISM, 1).add(Aspects.AIR, 4));
        r.complex("minecraft:oak_trapdoor", new AspectList().add(Aspects.MOTION, 1));
        r.complex("minecraft:furnace", new AspectList().add(Aspects.FIRE, 4));
        r.complex("minecraft:furnace", new AspectList().add(Aspects.FIRE, 2));
        r.complex("minecraft:enchanting_table", new AspectList().add(Aspects.MAGIC, 8).add(Aspects.CRAFT, 4));
        r.item("minecraft:crafting_table", new AspectList().add(Aspects.CRAFT, 4));
        r.complex("minecraft:clock", new AspectList().add(Aspects.MECHANISM, 2));
        r.item("minecraft:anvil", new AspectList().add(Aspects.METAL, 64).add(Aspects.CRAFT, 2).add(Aspects.TOOL, 2));
        r.item("minecraft:chipped_anvil", new AspectList().add(Aspects.METAL, 64).add(Aspects.CRAFT, 2).add(Aspects.TOOL, 2));
        r.item("minecraft:damaged_anvil", new AspectList().add(Aspects.METAL, 64).add(Aspects.CRAFT, 2).add(Aspects.TOOL, 2));
        r.complex("minecraft:beacon", new AspectList().add(Aspects.AURA, 2).add(Aspects.MAGIC, 2).add(Aspects.EXCHANGE, 2));
        r.complex("minecraft:oak_button", new AspectList().add(Aspects.MECHANISM, 1));
        r.complex("minecraft:carrot_on_a_stick", new AspectList().add(Aspects.TRAVEL, 4));
        r.complex("minecraft:flower_pot", new AspectList().add(Aspects.VOID, 1).add(Aspects.PLANT, 1));
        r.complex("minecraft:golden_carrot", new AspectList().add(Aspects.SENSES, 2));
        r.complex("minecraft:ender_chest", new AspectList().merge(Aspects.EXCHANGE, 2).merge(Aspects.TRAVEL, 2).merge(Aspects.VOID, 4));
        r.complex("minecraft:hopper", new AspectList().merge(Aspects.MECHANISM, 1).merge(Aspects.EXCHANGE, 1).merge(Aspects.VOID, 1));
        r.complex("minecraft:dropper", new AspectList().merge(Aspects.MECHANISM, 1).merge(Aspects.EXCHANGE, 1).merge(Aspects.VOID, 1));
        r.complex("minecraft:dispenser", new AspectList().merge(Aspects.MECHANISM, 1).merge(Aspects.EXCHANGE, 1).merge(Aspects.VOID, 1));
        r.item("minecraft:tripwire_hook", new AspectList().add(Aspects.SENSES, 1).add(Aspects.MECHANISM, 1).add(Aspects.TRAP, 1));
        r.complex("minecraft:daylight_detector", new AspectList().merge(Aspects.SENSES, 2).merge(Aspects.LIGHT, 3).merge(Aspects.MECHANISM, 3));
        r.complex("thaumcraft:table", new AspectList().add(Aspects.TOOL, 1));
        r.item("thaumcraft:arcane_workbench", r.copy("thaumcraft:table").add(Aspects.CRAFT, 4));
        r.item("thaumcraft:native_iron_cluster", new AspectList().add(Aspects.ORDER, 1).add(Aspects.METAL, 6).add(Aspects.EARTH, 1));
        r.item("thaumcraft:native_gold_cluster", new AspectList().add(Aspects.ORDER, 1).add(Aspects.METAL, 4).add(Aspects.EARTH, 1).add(Aspects.GREED, 2));
        r.item("thaumcraft:native_cinnabar_cluster", new AspectList().add(Aspects.ORDER, 1).add(Aspects.METAL, 4).add(Aspects.EARTH, 1).add(Aspects.EXCHANGE, 4).add(Aspects.POISON, 2));
        r.item("thaumcraft:quicksilver_drop", new AspectList().add(Aspects.METAL, 1));
        r.item("thaumcraft:thaumium_nugget", new AspectList().add(Aspects.METAL, 1));
        r.item("thaumcraft:cinnabar_ore", new AspectList().add(Aspects.EARTH, 1).add(Aspects.METAL, 2).add(Aspects.EXCHANGE, 2).add(Aspects.POISON, 1));
        r.item("thaumcraft:amber_ore", new AspectList().add(Aspects.EARTH, 1).add(Aspects.TRAP, 3).add(Aspects.CRYSTAL, 2));
        r.item("thaumcraft:infused_stone_air", new AspectList().add(Aspects.EARTH, 1).add(Aspects.AIR, 3).add(Aspects.CRYSTAL, 2));
        r.item("thaumcraft:infused_stone_fire", new AspectList().add(Aspects.EARTH, 1).add(Aspects.FIRE, 3).add(Aspects.CRYSTAL, 2));
        r.item("thaumcraft:infused_stone_water", new AspectList().add(Aspects.EARTH, 1).add(Aspects.WATER, 3).add(Aspects.CRYSTAL, 2));
        r.item("thaumcraft:infused_stone_earth", new AspectList().add(Aspects.EARTH, 1).add(Aspects.EARTH, 3).add(Aspects.CRYSTAL, 2));
        r.item("thaumcraft:infused_stone_order", new AspectList().add(Aspects.EARTH, 1).add(Aspects.ORDER, 3).add(Aspects.CRYSTAL, 2));
        r.item("thaumcraft:infused_stone_entropy", new AspectList().add(Aspects.EARTH, 1).add(Aspects.ENTROPY, 3).add(Aspects.CRYSTAL, 2));
        r.item("thaumcraft:taint_crust", new AspectList().add(Aspects.TREE, 1).add(Aspects.TAINT, 3));
        r.item("thaumcraft:taint_soil", new AspectList().add(Aspects.EARTH, 1).add(Aspects.TAINT, 3));
        r.item("thaumcraft:taint_fibres", new AspectList().add(Aspects.LIFE, 1).add(Aspects.TAINT, 2));
        r.item("thaumcraft:obsidian_totem", new AspectList().add(Aspects.EARTH, 4).add(Aspects.DARKNESS, 2).add(Aspects.ELDRITCH, 2));
        r.item("thaumcraft:greatwood_log", new AspectList().add(Aspects.TREE, 3).add(Aspects.MAGIC, 1));
        r.item("thaumcraft:silverwood_log", new AspectList().add(Aspects.TREE, 3).add(Aspects.MAGIC, 1).add(Aspects.ORDER, 1));
        r.item("thaumcraft:greatwood_leaves", new AspectList().add(Aspects.PLANT, 1));
        r.item("thaumcraft:silverwood_leaves", new AspectList().add(Aspects.PLANT, 1));
        r.item("thaumcraft:greatwood_sapling", new AspectList().add(Aspects.PLANT, 2).add(Aspects.TREE, 1).add(Aspects.MAGIC, 1));
        r.item("thaumcraft:silverwood_sapling", new AspectList().add(Aspects.PLANT, 2).add(Aspects.TREE, 1).add(Aspects.MAGIC, 1));
        r.item("thaumcraft:shimmerleaf", new AspectList().add(Aspects.PLANT, 2).add(Aspects.EXCHANGE, 2).add(Aspects.MAGIC, 2));
        r.item("thaumcraft:cinderpearl", new AspectList().add(Aspects.PLANT, 2).add(Aspects.FIRE, 2).add(Aspects.MAGIC, 2));
        r.item("thaumcraft:vishroom", new AspectList().add(Aspects.PLANT, 2).add(Aspects.POISON, 1).add(Aspects.MAGIC, 2));
        r.item("thaumcraft:arcane_stone", new AspectList().add(Aspects.EARTH, 1).add(Aspects.MAGIC, 1));
        r.item("thaumcraft:arcane_stone_bricks", new AspectList().add(Aspects.EARTH, 1).add(Aspects.MAGIC, 1));
        r.item("thaumcraft:quicksilver", new AspectList().add(Aspects.METAL, 3).add(Aspects.POISON, 1).add(Aspects.EXCHANGE, 2));
        r.item("thaumcraft:zombie_brain", new AspectList().add(Aspects.FLESH, 2).add(Aspects.MIND, 4).add(Aspects.UNDEAD, 2));
        r.item("thaumcraft:amber", new AspectList().add(Aspects.TRAP, 2).add(Aspects.CRYSTAL, 2));
        r.item("thaumcraft:knowledge_fragment", new AspectList().add(Aspects.MIND, 8));
        r.item("thaumcraft:tainted_goo", new AspectList().add(Aspects.TAINT, 3).add(Aspects.SLIME, 1));
        r.item("thaumcraft:taint_tendril", new AspectList().add(Aspects.TAINT, 2).add(Aspects.GREED, 1).add(Aspects.HUNGER, 1));
        r.item("thaumcraft:gold_coin", new AspectList().add(Aspects.GREED, 1));
        r.item("thaumcraft:loot_bag", new AspectList().add(Aspects.GREED, 8));
        r.item("thaumcraft:loot_bag_uncommon", new AspectList().add(Aspects.GREED, 16));
        r.item("thaumcraft:loot_bag_rare", new AspectList().add(Aspects.GREED, 32));
        r.item("thaumcraft:nugget_beef", new AspectList().add(Aspects.HUNGER, 1));
        r.item("thaumcraft:nugget_chicken", new AspectList().add(Aspects.HUNGER, 1));
        r.item("thaumcraft:nugget_pork", new AspectList().add(Aspects.HUNGER, 1));
        r.item("thaumcraft:nugget_fish", new AspectList().add(Aspects.HUNGER, 1));
        r.complex("thaumcraft:triple_meat_treat", minus(new AspectList().add(Aspects.HEAL, 1), Aspects.HUNGER, 1));
        r.item("thaumcraft:shard_air", new AspectList().add(Aspects.MAGIC, 1).add(Aspects.AIR, 2).add(Aspects.CRYSTAL, 1));
        r.item("thaumcraft:shard_fire", new AspectList().add(Aspects.MAGIC, 1).add(Aspects.FIRE, 2).add(Aspects.CRYSTAL, 1));
        r.item("thaumcraft:shard_water", new AspectList().add(Aspects.MAGIC, 1).add(Aspects.WATER, 2).add(Aspects.CRYSTAL, 1));
        r.item("thaumcraft:shard_earth", new AspectList().add(Aspects.MAGIC, 1).add(Aspects.EARTH, 2).add(Aspects.CRYSTAL, 1));
        r.item("thaumcraft:shard_order", new AspectList().add(Aspects.MAGIC, 1).add(Aspects.ORDER, 2).add(Aspects.CRYSTAL, 1));
        r.item("thaumcraft:shard_entropy", new AspectList().add(Aspects.MAGIC, 1).add(Aspects.ENTROPY, 2).add(Aspects.CRYSTAL, 1));
        r.item("thaumcraft:salis_mundus", r.copy("thaumcraft:shard_balanced").add(Aspects.MAGIC, 2));
        r.item("thaumcraft:crucible", r.copy("minecraft:cauldron").add(Aspects.CRAFT, 4).add(Aspects.MAGIC, 4));
        r.item("thaumcraft:white_tallow_candle", new AspectList().add(Aspects.LIGHT, 2).add(Aspects.FLESH, 1).add(Aspects.MAGIC, 1));
        r.item("thaumcraft:thaumonomicon", r.copy("minecraft:bookshelf").add(Aspects.MAGIC, 2).merge(Aspects.MIND, 2));
        r.item("thaumcraft:phial", new AspectList().add(Aspects.VOID, 1));
        r.item("thaumcraft:wisp_essence", new AspectList().add(Aspects.AURA, 2));
        r.item("thaumcraft:crystal_essence", new AspectList());
        r.complex("thaumcraft:goggles", new AspectList().add(Aspects.SENSES, 4));
        r.complex("thaumcraft:arcane_ear", new AspectList().add(Aspects.SENSES, 4));
        r.item("thaumcraft:apprentice_ring_air", new AspectList().add(Aspects.MAGIC, 5));
        r.item("thaumcraft:focus_pech", new AspectList().add(Aspects.MAGIC, 5).add(Aspects.POISON, 5).add(Aspects.ENTROPY, 5).add(Aspects.ELDRITCH, 5).add(Aspects.WEAPON, 5));
        r.item("thaumcraft:eldritch_eye", new AspectList().add(Aspects.ELDRITCH, 5).add(Aspects.AURA, 3).add(Aspects.MAGIC, 3).add(Aspects.SENSES, 3).add(Aspects.SOUL, 3));
        r.item("thaumcraft:crimson_rites", new AspectList().add(Aspects.MIND, 5).add(Aspects.MAGIC, 3).add(Aspects.ELDRITCH, 3).add(Aspects.SOUL, 3));
        r.item("thaumcraft:runed_tablet", new AspectList().add(Aspects.TRAP, 4).add(Aspects.MIND, 4).add(Aspects.MECHANISM, 4));
        r.item("thaumcraft:primordial_pearl", new AspectList().add(Aspects.AIR, 16).add(Aspects.EARTH, 16).add(Aspects.FIRE, 16).add(Aspects.WATER, 16).add(Aspects.ORDER, 16).add(Aspects.ENTROPY, 16));
        r.item("thaumcraft:glowing_crusted_stone", new AspectList().add(Aspects.LIGHT, 1).add(Aspects.EARTH, 1).add(Aspects.ELDRITCH, 1));
        r.item("thaumcraft:ancient_stone", new AspectList().add(Aspects.EARTH, 1).add(Aspects.ELDRITCH, 1));
        r.item("thaumcraft:ancient_rock", new AspectList().add(Aspects.EARTH, 1).add(Aspects.ELDRITCH, 1));
    }

    static void blocks(ObjectAspects.Registrar r) {
        r.block("minecraft:fire", new AspectList().add(Aspects.FIRE, 4));
        r.block("minecraft:water", new AspectList().add(Aspects.WATER, 4));
        r.block("minecraft:lava", new AspectList().add(Aspects.FIRE, 3).add(Aspects.EARTH, 1));
        r.block("minecraft:nether_portal", new AspectList().add(Aspects.FIRE, 4).add(Aspects.TRAVEL, 4));
        r.block("minecraft:end_portal", new AspectList().add(Aspects.ELDRITCH, 4).add(Aspects.TRAVEL, 4));
        r.block("thaumcraft:eldritch_altar", new AspectList().add(Aspects.VOID, 8).add(Aspects.ELDRITCH, 8).add(Aspects.SENSES, 4));
        r.block("thaumcraft:eldritch_obelisk", new AspectList().add(Aspects.VOID, 8).add(Aspects.ELDRITCH, 8).add(Aspects.SENSES, 4));
        r.block("thaumcraft:eldritch_obelisk_upper", new AspectList().add(Aspects.VOID, 8).add(Aspects.ELDRITCH, 8).add(Aspects.SENSES, 4));
        r.block("thaumcraft:eldritch_capstone", new AspectList().add(Aspects.VOID, 8).add(Aspects.ELDRITCH, 8).add(Aspects.SENSES, 4));
        r.block("thaumcraft:glyphed_stone", new AspectList().add(Aspects.VOID, 8).add(Aspects.ELDRITCH, 8).add(Aspects.SENSES, 4));
        r.block("thaumcraft:eldritch_deco", new AspectList().add(Aspects.VOID, 8).add(Aspects.ELDRITCH, 8).add(Aspects.SENSES, 4));
        r.block("thaumcraft:eldritch_capstone", new AspectList().add(Aspects.VOID, 4).add(Aspects.ELDRITCH, 4));
        r.block("thaumcraft:glyphed_stone", new AspectList().add(Aspects.MIND, 2).add(Aspects.EARTH, 1).add(Aspects.ELDRITCH, 1));
        r.block("thaumcraft:eldritch_deco", new AspectList().add(Aspects.METAL, 2).add(Aspects.MECHANISM, 2).add(Aspects.ELDRITCH, 1));
    }

    /** O {@code AspectList.remove(aspecto, n)} do original: tira, e some com o que ficar em zero. */
    private static AspectList minus(AspectList list, Aspect aspect, int amount) {
        list.remove(aspect, amount);
        return list;
    }
}
