package net.thaumcraft.api.aspects;

/**
 * Os aspectos do que o Minecraft ganhou depois da 1.7.10 — a pedra-profunda, o cobre que envelhece, a ametista, os
 * corais, o sculk, as plantas novas, as câmaras de provação, o enxofre e o cinábrio.
 *
 * <p><b>Este arquivo é gerado</b> pelo {@code scratchpad/aspectos-novos.js}. O original só conhecia o jogo de 2014;
 * estas são as anotações que faltavam, no mesmo tom das dele. Só entram as <b>bases</b>: o que sai de receita herda
 * os aspectos do que entra, como o próprio mod deduz.
 */
final class NewItemsAspectsTable {
    private NewItemsAspectsTable() {
    }

    static void register(ObjectAspects.Registrar r) {
        r.item("minecraft:deepslate", new AspectList().add(Aspects.EARTH, 2).add(Aspects.DARKNESS, 1));
        r.item("minecraft:cobbled_deepslate", new AspectList().add(Aspects.EARTH, 1).add(Aspects.ENTROPY, 1).add(Aspects.DARKNESS, 1));
        r.item("minecraft:infested_deepslate", new AspectList().add(Aspects.EARTH, 2).add(Aspects.DARKNESS, 1).add(Aspects.BEAST, 2));
        r.item("minecraft:reinforced_deepslate", new AspectList().add(Aspects.EARTH, 4).add(Aspects.DARKNESS, 2).add(Aspects.MAGIC, 4));
        r.item("minecraft:calcite", new AspectList().add(Aspects.EARTH, 1).add(Aspects.CRYSTAL, 2));
        r.item("minecraft:tuff", new AspectList().add(Aspects.EARTH, 2).add(Aspects.FIRE, 1));
        r.item("minecraft:basalt", new AspectList().add(Aspects.EARTH, 2).add(Aspects.FIRE, 1));
        r.item("minecraft:smooth_basalt", new AspectList().add(Aspects.EARTH, 2).add(Aspects.FIRE, 1));
        r.item("minecraft:blackstone", new AspectList().add(Aspects.EARTH, 2).add(Aspects.DARKNESS, 1));
        r.item("minecraft:gilded_blackstone", new AspectList().add(Aspects.EARTH, 2).add(Aspects.DARKNESS, 1).add(Aspects.GREED, 2));
        r.item("minecraft:crying_obsidian", new AspectList().add(Aspects.EARTH, 3).add(Aspects.DARKNESS, 2).add(Aspects.MAGIC, 2));
        r.item("minecraft:soul_soil", new AspectList().add(Aspects.EARTH, 1).add(Aspects.SOUL, 2));
        r.item("minecraft:rooted_dirt", new AspectList().add(Aspects.EARTH, 2).add(Aspects.PLANT, 1));
        r.item("minecraft:mud", new AspectList().add(Aspects.EARTH, 1).add(Aspects.WATER, 1));
        r.item("minecraft:dirt_path", new AspectList().add(Aspects.EARTH, 2).add(Aspects.TRAVEL, 1));
        r.item("minecraft:crimson_nylium", new AspectList().add(Aspects.EARTH, 1).add(Aspects.PLANT, 1).add(Aspects.FIRE, 1));
        r.item("minecraft:warped_nylium", new AspectList().add(Aspects.EARTH, 1).add(Aspects.PLANT, 1).add(Aspects.ELDRITCH, 1));
        r.item("minecraft:suspicious_sand", new AspectList().add(Aspects.EARTH, 1).add(Aspects.ENTROPY, 1).add(Aspects.GREED, 1));
        r.item("minecraft:suspicious_gravel", new AspectList().add(Aspects.EARTH, 2).add(Aspects.GREED, 1));
        r.item("minecraft:deepslate_coal_ore", new AspectList().add(Aspects.EARTH, 1).add(Aspects.FIRE, 2).add(Aspects.DARKNESS, 1));
        r.item("minecraft:ancient_debris", new AspectList().add(Aspects.EARTH, 2).add(Aspects.METAL, 4).add(Aspects.DARKNESS, 2));
        r.item("minecraft:netherite_scrap", new AspectList().add(Aspects.METAL, 5).add(Aspects.FIRE, 2).add(Aspects.DARKNESS, 1));
        r.item("minecraft:smooth_stone", new AspectList().add(Aspects.EARTH, 2).add(Aspects.FIRE, 1));
        r.item("minecraft:smooth_sandstone", new AspectList().add(Aspects.EARTH, 2).add(Aspects.FIRE, 1));
        r.item("minecraft:smooth_red_sandstone", new AspectList().add(Aspects.EARTH, 2).add(Aspects.FIRE, 1));
        r.item("minecraft:smooth_quartz", new AspectList().add(Aspects.EARTH, 2).add(Aspects.FIRE, 1));
        r.item("minecraft:petrified_oak_slab", new AspectList().add(Aspects.EARTH, 2).add(Aspects.FIRE, 1));
        r.item("minecraft:cracked_deepslate_bricks", new AspectList().add(Aspects.EARTH, 2).add(Aspects.ENTROPY, 1));
        r.item("minecraft:cracked_deepslate_tiles", new AspectList().add(Aspects.EARTH, 2).add(Aspects.ENTROPY, 1));
        r.item("minecraft:cracked_nether_bricks", new AspectList().add(Aspects.EARTH, 2).add(Aspects.ENTROPY, 1));
        r.item("minecraft:cracked_polished_blackstone_bricks", new AspectList().add(Aspects.EARTH, 2).add(Aspects.ENTROPY, 1));
        r.item("minecraft:pointed_dripstone", new AspectList().add(Aspects.EARTH, 2).add(Aspects.WATER, 1).add(Aspects.WEAPON, 1));
        r.item("minecraft:heavy_core", new AspectList().add(Aspects.EARTH, 4).add(Aspects.METAL, 4).add(Aspects.MOTION, 4));
        r.item("minecraft:sponge", new AspectList().add(Aspects.WATER, 4).add(Aspects.VOID, 2).add(Aspects.LIFE, 1));
        r.item("minecraft:wet_sponge", new AspectList().add(Aspects.WATER, 6).add(Aspects.VOID, 2).add(Aspects.LIFE, 1));
        r.item("minecraft:cinnabar", new AspectList().add(Aspects.EARTH, 2).add(Aspects.METAL, 2).add(Aspects.POISON, 2));
        r.item("minecraft:sulfur", new AspectList().add(Aspects.EARTH, 1).add(Aspects.FIRE, 2).add(Aspects.POISON, 1));
        r.item("minecraft:potent_sulfur", new AspectList().add(Aspects.EARTH, 1).add(Aspects.FIRE, 4).add(Aspects.POISON, 2).add(Aspects.ENERGY, 2));
        r.item("minecraft:sulfur_spike", new AspectList().add(Aspects.FIRE, 2).add(Aspects.POISON, 1).add(Aspects.WEAPON, 1));
        r.item("minecraft:granite", new AspectList().add(Aspects.EARTH, 2));
        r.item("minecraft:diorite", new AspectList().add(Aspects.EARTH, 2));
        r.item("minecraft:andesite", new AspectList().add(Aspects.EARTH, 2));
        r.item("minecraft:dripstone_block", new AspectList().add(Aspects.EARTH, 2).add(Aspects.WATER, 1));
        r.item("minecraft:moss_carpet", new AspectList().add(Aspects.PLANT, 1));
        r.item("minecraft:bamboo_block", new AspectList().add(Aspects.TREE, 3));
        r.item("minecraft:amethyst_shard", new AspectList().add(Aspects.CRYSTAL, 3).add(Aspects.SENSES, 1));
        r.item("minecraft:budding_amethyst", new AspectList().add(Aspects.CRYSTAL, 4).add(Aspects.EARTH, 2).add(Aspects.LIFE, 2));
        r.item("minecraft:small_amethyst_bud", new AspectList().add(Aspects.CRYSTAL, 2).add(Aspects.SENSES, 1));
        r.item("minecraft:medium_amethyst_bud", new AspectList().add(Aspects.CRYSTAL, 2).add(Aspects.SENSES, 1));
        r.item("minecraft:large_amethyst_bud", new AspectList().add(Aspects.CRYSTAL, 2).add(Aspects.SENSES, 1));
        r.item("minecraft:amethyst_cluster", new AspectList().add(Aspects.CRYSTAL, 4).add(Aspects.SENSES, 2));
        r.item("minecraft:echo_shard", new AspectList().add(Aspects.CRYSTAL, 3).add(Aspects.SENSES, 3).add(Aspects.DARKNESS, 2));
        r.item("minecraft:prismarine_shard", new AspectList().add(Aspects.CRYSTAL, 2).add(Aspects.WATER, 2));
        r.item("minecraft:prismarine_crystals", new AspectList().add(Aspects.CRYSTAL, 2).add(Aspects.WATER, 2).add(Aspects.LIGHT, 2));
        r.item("minecraft:heart_of_the_sea", new AspectList().add(Aspects.WATER, 6).add(Aspects.MAGIC, 4).add(Aspects.GREED, 2));
        r.item("minecraft:nautilus_shell", new AspectList().add(Aspects.WATER, 3).add(Aspects.BEAST, 2).add(Aspects.ARMOR, 1));
        r.item("minecraft:exposed_copper", new AspectList().add(Aspects.METAL, 3).add(Aspects.EXCHANGE, 1).add(Aspects.ENTROPY, 1).add(Aspects.WATER, 1));
        r.item("minecraft:weathered_copper", new AspectList().add(Aspects.METAL, 3).add(Aspects.EXCHANGE, 1).add(Aspects.ENTROPY, 2).add(Aspects.WATER, 2));
        r.item("minecraft:oxidized_copper", new AspectList().add(Aspects.METAL, 3).add(Aspects.EXCHANGE, 1).add(Aspects.ENTROPY, 3).add(Aspects.WATER, 3));
        r.item("minecraft:exposed_copper_bars", new AspectList().add(Aspects.METAL, 2).add(Aspects.ENTROPY, 1).add(Aspects.WATER, 1));
        r.item("minecraft:weathered_copper_bars", new AspectList().add(Aspects.METAL, 2).add(Aspects.ENTROPY, 2).add(Aspects.WATER, 2));
        r.item("minecraft:oxidized_copper_bars", new AspectList().add(Aspects.METAL, 2).add(Aspects.ENTROPY, 3).add(Aspects.WATER, 3));
        r.item("minecraft:exposed_copper_chain", new AspectList().add(Aspects.METAL, 2).add(Aspects.MECHANISM, 1).add(Aspects.ENTROPY, 1).add(Aspects.WATER, 1));
        r.item("minecraft:weathered_copper_chain", new AspectList().add(Aspects.METAL, 2).add(Aspects.MECHANISM, 1).add(Aspects.ENTROPY, 2).add(Aspects.WATER, 2));
        r.item("minecraft:oxidized_copper_chain", new AspectList().add(Aspects.METAL, 2).add(Aspects.MECHANISM, 1).add(Aspects.ENTROPY, 3).add(Aspects.WATER, 3));
        r.item("minecraft:exposed_copper_door", new AspectList().add(Aspects.METAL, 3).add(Aspects.MECHANISM, 1).add(Aspects.ENTROPY, 1).add(Aspects.WATER, 1));
        r.item("minecraft:weathered_copper_door", new AspectList().add(Aspects.METAL, 3).add(Aspects.MECHANISM, 1).add(Aspects.ENTROPY, 2).add(Aspects.WATER, 2));
        r.item("minecraft:oxidized_copper_door", new AspectList().add(Aspects.METAL, 3).add(Aspects.MECHANISM, 1).add(Aspects.ENTROPY, 3).add(Aspects.WATER, 3));
        r.item("minecraft:exposed_copper_trapdoor", new AspectList().add(Aspects.METAL, 2).add(Aspects.MECHANISM, 1).add(Aspects.ENTROPY, 1).add(Aspects.WATER, 1));
        r.item("minecraft:weathered_copper_trapdoor", new AspectList().add(Aspects.METAL, 2).add(Aspects.MECHANISM, 1).add(Aspects.ENTROPY, 2).add(Aspects.WATER, 2));
        r.item("minecraft:oxidized_copper_trapdoor", new AspectList().add(Aspects.METAL, 2).add(Aspects.MECHANISM, 1).add(Aspects.ENTROPY, 3).add(Aspects.WATER, 3));
        r.item("minecraft:exposed_copper_lantern", new AspectList().add(Aspects.METAL, 2).add(Aspects.LIGHT, 3).add(Aspects.ENTROPY, 1).add(Aspects.WATER, 1));
        r.item("minecraft:weathered_copper_lantern", new AspectList().add(Aspects.METAL, 2).add(Aspects.LIGHT, 3).add(Aspects.ENTROPY, 2).add(Aspects.WATER, 2));
        r.item("minecraft:oxidized_copper_lantern", new AspectList().add(Aspects.METAL, 2).add(Aspects.LIGHT, 3).add(Aspects.ENTROPY, 3).add(Aspects.WATER, 3));
        r.item("minecraft:exposed_copper_chest", new AspectList().add(Aspects.METAL, 3).add(Aspects.VOID, 2).add(Aspects.ENTROPY, 1).add(Aspects.WATER, 1));
        r.item("minecraft:weathered_copper_chest", new AspectList().add(Aspects.METAL, 3).add(Aspects.VOID, 2).add(Aspects.ENTROPY, 2).add(Aspects.WATER, 2));
        r.item("minecraft:oxidized_copper_chest", new AspectList().add(Aspects.METAL, 3).add(Aspects.VOID, 2).add(Aspects.ENTROPY, 3).add(Aspects.WATER, 3));
        r.item("minecraft:copper_golem_statue", new AspectList().add(Aspects.METAL, 4).add(Aspects.MECHANISM, 2));
        r.item("minecraft:exposed_copper_golem_statue", new AspectList().add(Aspects.METAL, 4).add(Aspects.MECHANISM, 2).add(Aspects.ENTROPY, 1).add(Aspects.WATER, 1));
        r.item("minecraft:weathered_copper_golem_statue", new AspectList().add(Aspects.METAL, 4).add(Aspects.MECHANISM, 2).add(Aspects.ENTROPY, 2).add(Aspects.WATER, 2));
        r.item("minecraft:oxidized_copper_golem_statue", new AspectList().add(Aspects.METAL, 4).add(Aspects.MECHANISM, 2).add(Aspects.ENTROPY, 3).add(Aspects.WATER, 3));
        r.item("minecraft:exposed_lightning_rod", new AspectList().add(Aspects.METAL, 3).add(Aspects.ENERGY, 3).add(Aspects.WEATHER, 2).add(Aspects.ENTROPY, 1).add(Aspects.WATER, 1));
        r.item("minecraft:weathered_lightning_rod", new AspectList().add(Aspects.METAL, 3).add(Aspects.ENERGY, 3).add(Aspects.WEATHER, 2).add(Aspects.ENTROPY, 2).add(Aspects.WATER, 2));
        r.item("minecraft:oxidized_lightning_rod", new AspectList().add(Aspects.METAL, 3).add(Aspects.ENERGY, 3).add(Aspects.WEATHER, 2).add(Aspects.ENTROPY, 3).add(Aspects.WATER, 3));
        r.item("minecraft:cornflower", new AspectList().add(Aspects.PLANT, 1).add(Aspects.LIFE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:lily_of_the_valley", new AspectList().add(Aspects.PLANT, 1).add(Aspects.LIFE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:torchflower", new AspectList().add(Aspects.PLANT, 1).add(Aspects.LIFE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:open_eyeblossom", new AspectList().add(Aspects.PLANT, 1).add(Aspects.LIFE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:closed_eyeblossom", new AspectList().add(Aspects.PLANT, 1).add(Aspects.LIFE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:cactus_flower", new AspectList().add(Aspects.PLANT, 1).add(Aspects.LIFE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:wildflowers", new AspectList().add(Aspects.PLANT, 1).add(Aspects.LIFE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:pink_petals", new AspectList().add(Aspects.PLANT, 1).add(Aspects.LIFE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:spore_blossom", new AspectList().add(Aspects.PLANT, 1).add(Aspects.LIFE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:pitcher_plant", new AspectList().add(Aspects.PLANT, 1).add(Aspects.LIFE, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:wither_rose", new AspectList().add(Aspects.PLANT, 1).add(Aspects.DEATH, 2).add(Aspects.POISON, 2));
        r.item("minecraft:bush", new AspectList().add(Aspects.PLANT, 1));
        r.item("minecraft:short_dry_grass", new AspectList().add(Aspects.PLANT, 1));
        r.item("minecraft:tall_dry_grass", new AspectList().add(Aspects.PLANT, 1));
        r.item("minecraft:leaf_litter", new AspectList().add(Aspects.PLANT, 1));
        r.item("minecraft:firefly_bush", new AspectList().add(Aspects.PLANT, 1).add(Aspects.LIGHT, 2).add(Aspects.BEAST, 1));
        r.item("minecraft:moss_block", new AspectList().add(Aspects.PLANT, 2).add(Aspects.EARTH, 1));
        r.item("minecraft:pale_moss_block", new AspectList().add(Aspects.PLANT, 2).add(Aspects.EARTH, 1));
        r.item("minecraft:pale_hanging_moss", new AspectList().add(Aspects.PLANT, 1).add(Aspects.DARKNESS, 1));
        r.item("minecraft:hanging_roots", new AspectList().add(Aspects.PLANT, 1).add(Aspects.EARTH, 1));
        r.item("minecraft:mangrove_roots", new AspectList().add(Aspects.TREE, 2).add(Aspects.PLANT, 1).add(Aspects.WATER, 1));
        r.item("minecraft:bamboo", new AspectList().add(Aspects.PLANT, 1).add(Aspects.TREE, 1));
        r.item("minecraft:stripped_bamboo_block", new AspectList().add(Aspects.TREE, 3));
        r.item("minecraft:big_dripleaf", new AspectList().add(Aspects.PLANT, 2).add(Aspects.WATER, 1));
        r.item("minecraft:small_dripleaf", new AspectList().add(Aspects.PLANT, 2).add(Aspects.WATER, 1));
        r.item("minecraft:kelp", new AspectList().add(Aspects.PLANT, 1).add(Aspects.WATER, 1));
        r.item("minecraft:seagrass", new AspectList().add(Aspects.PLANT, 1).add(Aspects.WATER, 1));
        r.item("minecraft:sea_pickle", new AspectList().add(Aspects.PLANT, 1).add(Aspects.WATER, 1).add(Aspects.LIGHT, 2));
        r.item("minecraft:glow_lichen", new AspectList().add(Aspects.PLANT, 1).add(Aspects.LIGHT, 2));
        r.item("minecraft:crimson_fungus", new AspectList().add(Aspects.PLANT, 2).add(Aspects.FIRE, 1));
        r.item("minecraft:warped_fungus", new AspectList().add(Aspects.PLANT, 2).add(Aspects.FIRE, 1));
        r.item("minecraft:crimson_roots", new AspectList().add(Aspects.PLANT, 1).add(Aspects.FIRE, 1));
        r.item("minecraft:warped_roots", new AspectList().add(Aspects.PLANT, 1).add(Aspects.FIRE, 1));
        r.item("minecraft:nether_sprouts", new AspectList().add(Aspects.PLANT, 1).add(Aspects.FIRE, 1));
        r.item("minecraft:weeping_vines", new AspectList().add(Aspects.PLANT, 1).add(Aspects.FIRE, 1).add(Aspects.MOTION, 1));
        r.item("minecraft:twisting_vines", new AspectList().add(Aspects.PLANT, 1).add(Aspects.FIRE, 1).add(Aspects.MOTION, 1));
        r.item("minecraft:warped_wart_block", new AspectList().add(Aspects.PLANT, 2).add(Aspects.ELDRITCH, 1));
        r.item("minecraft:shroomlight", new AspectList().add(Aspects.PLANT, 2).add(Aspects.LIGHT, 4));
        r.item("minecraft:chorus_plant", new AspectList().add(Aspects.PLANT, 2).add(Aspects.ELDRITCH, 1).add(Aspects.TRAVEL, 1));
        r.item("minecraft:chorus_flower", new AspectList().add(Aspects.PLANT, 2).add(Aspects.ELDRITCH, 2).add(Aspects.LIFE, 1));
        r.item("minecraft:chorus_fruit", new AspectList().add(Aspects.CROP, 1).add(Aspects.HUNGER, 1).add(Aspects.TRAVEL, 2).add(Aspects.ELDRITCH, 1));
        r.item("minecraft:popped_chorus_fruit", new AspectList().add(Aspects.CRAFT, 1).add(Aspects.ELDRITCH, 2).add(Aspects.TRAVEL, 1));
        r.item("minecraft:sweet_berries", new AspectList().add(Aspects.CROP, 1).add(Aspects.HUNGER, 1).add(Aspects.LIFE, 1));
        r.item("minecraft:glow_berries", new AspectList().add(Aspects.CROP, 1).add(Aspects.HUNGER, 1).add(Aspects.LIGHT, 2));
        r.item("minecraft:beetroot", new AspectList().add(Aspects.CROP, 1).add(Aspects.HUNGER, 1).add(Aspects.LIFE, 1));
        r.item("minecraft:beetroot_seeds", new AspectList().add(Aspects.CROP, 1).add(Aspects.LIFE, 1));
        r.item("minecraft:torchflower_seeds", new AspectList().add(Aspects.CROP, 1).add(Aspects.LIFE, 1));
        r.item("minecraft:pitcher_pod", new AspectList().add(Aspects.CROP, 1).add(Aspects.LIFE, 1));
        r.item("minecraft:frogspawn", new AspectList().add(Aspects.LIFE, 2).add(Aspects.WATER, 2).add(Aspects.BEAST, 1));
        r.item("minecraft:honeycomb", new AspectList().add(Aspects.CROP, 1).add(Aspects.BEAST, 1).add(Aspects.CRAFT, 2));
        r.item("minecraft:bee_nest", new AspectList().add(Aspects.TREE, 2).add(Aspects.BEAST, 2).add(Aspects.CROP, 1));
        r.item("minecraft:ochre_froglight", new AspectList().add(Aspects.LIGHT, 4).add(Aspects.BEAST, 2).add(Aspects.FLESH, 1));
        r.item("minecraft:verdant_froglight", new AspectList().add(Aspects.LIGHT, 4).add(Aspects.BEAST, 2).add(Aspects.FLESH, 1));
        r.item("minecraft:pearlescent_froglight", new AspectList().add(Aspects.LIGHT, 4).add(Aspects.BEAST, 2).add(Aspects.FLESH, 1));
        r.item("minecraft:tube_coral", new AspectList().add(Aspects.WATER, 2).add(Aspects.LIFE, 2).add(Aspects.PLANT, 1));
        r.item("minecraft:tube_coral_block", new AspectList().add(Aspects.WATER, 2).add(Aspects.LIFE, 2).add(Aspects.PLANT, 1));
        r.item("minecraft:tube_coral_fan", new AspectList().add(Aspects.WATER, 2).add(Aspects.LIFE, 2).add(Aspects.PLANT, 1));
        r.item("minecraft:dead_tube_coral", new AspectList().add(Aspects.WATER, 1).add(Aspects.DEATH, 2).add(Aspects.ENTROPY, 1));
        r.item("minecraft:dead_tube_coral_block", new AspectList().add(Aspects.WATER, 1).add(Aspects.DEATH, 2).add(Aspects.ENTROPY, 1));
        r.item("minecraft:dead_tube_coral_fan", new AspectList().add(Aspects.WATER, 1).add(Aspects.DEATH, 2).add(Aspects.ENTROPY, 1));
        r.item("minecraft:brain_coral", new AspectList().add(Aspects.WATER, 2).add(Aspects.LIFE, 2).add(Aspects.PLANT, 1));
        r.item("minecraft:brain_coral_block", new AspectList().add(Aspects.WATER, 2).add(Aspects.LIFE, 2).add(Aspects.PLANT, 1));
        r.item("minecraft:brain_coral_fan", new AspectList().add(Aspects.WATER, 2).add(Aspects.LIFE, 2).add(Aspects.PLANT, 1));
        r.item("minecraft:dead_brain_coral", new AspectList().add(Aspects.WATER, 1).add(Aspects.DEATH, 2).add(Aspects.ENTROPY, 1));
        r.item("minecraft:dead_brain_coral_block", new AspectList().add(Aspects.WATER, 1).add(Aspects.DEATH, 2).add(Aspects.ENTROPY, 1));
        r.item("minecraft:dead_brain_coral_fan", new AspectList().add(Aspects.WATER, 1).add(Aspects.DEATH, 2).add(Aspects.ENTROPY, 1));
        r.item("minecraft:bubble_coral", new AspectList().add(Aspects.WATER, 2).add(Aspects.LIFE, 2).add(Aspects.PLANT, 1));
        r.item("minecraft:bubble_coral_block", new AspectList().add(Aspects.WATER, 2).add(Aspects.LIFE, 2).add(Aspects.PLANT, 1));
        r.item("minecraft:bubble_coral_fan", new AspectList().add(Aspects.WATER, 2).add(Aspects.LIFE, 2).add(Aspects.PLANT, 1));
        r.item("minecraft:dead_bubble_coral", new AspectList().add(Aspects.WATER, 1).add(Aspects.DEATH, 2).add(Aspects.ENTROPY, 1));
        r.item("minecraft:dead_bubble_coral_block", new AspectList().add(Aspects.WATER, 1).add(Aspects.DEATH, 2).add(Aspects.ENTROPY, 1));
        r.item("minecraft:dead_bubble_coral_fan", new AspectList().add(Aspects.WATER, 1).add(Aspects.DEATH, 2).add(Aspects.ENTROPY, 1));
        r.item("minecraft:fire_coral", new AspectList().add(Aspects.WATER, 2).add(Aspects.LIFE, 2).add(Aspects.PLANT, 1));
        r.item("minecraft:fire_coral_block", new AspectList().add(Aspects.WATER, 2).add(Aspects.LIFE, 2).add(Aspects.PLANT, 1));
        r.item("minecraft:fire_coral_fan", new AspectList().add(Aspects.WATER, 2).add(Aspects.LIFE, 2).add(Aspects.PLANT, 1));
        r.item("minecraft:dead_fire_coral", new AspectList().add(Aspects.WATER, 1).add(Aspects.DEATH, 2).add(Aspects.ENTROPY, 1));
        r.item("minecraft:dead_fire_coral_block", new AspectList().add(Aspects.WATER, 1).add(Aspects.DEATH, 2).add(Aspects.ENTROPY, 1));
        r.item("minecraft:dead_fire_coral_fan", new AspectList().add(Aspects.WATER, 1).add(Aspects.DEATH, 2).add(Aspects.ENTROPY, 1));
        r.item("minecraft:horn_coral", new AspectList().add(Aspects.WATER, 2).add(Aspects.LIFE, 2).add(Aspects.PLANT, 1));
        r.item("minecraft:horn_coral_block", new AspectList().add(Aspects.WATER, 2).add(Aspects.LIFE, 2).add(Aspects.PLANT, 1));
        r.item("minecraft:horn_coral_fan", new AspectList().add(Aspects.WATER, 2).add(Aspects.LIFE, 2).add(Aspects.PLANT, 1));
        r.item("minecraft:dead_horn_coral", new AspectList().add(Aspects.WATER, 1).add(Aspects.DEATH, 2).add(Aspects.ENTROPY, 1));
        r.item("minecraft:dead_horn_coral_block", new AspectList().add(Aspects.WATER, 1).add(Aspects.DEATH, 2).add(Aspects.ENTROPY, 1));
        r.item("minecraft:dead_horn_coral_fan", new AspectList().add(Aspects.WATER, 1).add(Aspects.DEATH, 2).add(Aspects.ENTROPY, 1));
        r.item("minecraft:sculk", new AspectList().add(Aspects.DEATH, 2).add(Aspects.DARKNESS, 2).add(Aspects.LIFE, 1));
        r.item("minecraft:sculk_vein", new AspectList().add(Aspects.DEATH, 1).add(Aspects.DARKNESS, 1).add(Aspects.PLANT, 1));
        r.item("minecraft:sculk_catalyst", new AspectList().add(Aspects.DEATH, 4).add(Aspects.DARKNESS, 3).add(Aspects.LIFE, 2));
        r.item("minecraft:sculk_shrieker", new AspectList().add(Aspects.DEATH, 3).add(Aspects.DARKNESS, 3).add(Aspects.SENSES, 3));
        r.item("minecraft:sculk_sensor", new AspectList().add(Aspects.DARKNESS, 2).add(Aspects.SENSES, 4).add(Aspects.MECHANISM, 2));
        r.item("minecraft:phantom_membrane", new AspectList().add(Aspects.FLESH, 2).add(Aspects.FLIGHT, 3).add(Aspects.UNDEAD, 2));
        r.item("minecraft:elytra", new AspectList().add(Aspects.FLIGHT, 8).add(Aspects.MAGIC, 4).add(Aspects.ELDRITCH, 2).add(Aspects.CLOTH, 2));
        r.item("minecraft:turtle_scute", new AspectList().add(Aspects.BEAST, 2).add(Aspects.ARMOR, 2));
        r.item("minecraft:armadillo_scute", new AspectList().add(Aspects.BEAST, 2).add(Aspects.ARMOR, 2));
        r.item("minecraft:rabbit", new AspectList().add(Aspects.FLESH, 3).add(Aspects.LIFE, 2).add(Aspects.BEAST, 1));
        r.item("minecraft:cooked_rabbit", new AspectList().add(Aspects.CRAFT, 1).add(Aspects.FLESH, 4).add(Aspects.HUNGER, 3));
        r.item("minecraft:rabbit_foot", new AspectList().add(Aspects.BEAST, 2).add(Aspects.MOTION, 3).add(Aspects.MAGIC, 2));
        r.item("minecraft:rabbit_hide", new AspectList().add(Aspects.BEAST, 1).add(Aspects.CLOTH, 2));
        r.item("minecraft:mutton", new AspectList().add(Aspects.FLESH, 4).add(Aspects.LIFE, 2).add(Aspects.BEAST, 1));
        r.item("minecraft:cooked_mutton", new AspectList().add(Aspects.CRAFT, 1).add(Aspects.FLESH, 4).add(Aspects.HUNGER, 4));
        r.item("minecraft:glow_ink_sac", new AspectList().add(Aspects.SENSES, 2).add(Aspects.LIGHT, 3));
        r.item("minecraft:shulker_shell", new AspectList().add(Aspects.ARMOR, 3).add(Aspects.VOID, 3).add(Aspects.ELDRITCH, 2));
        r.item("minecraft:breeze_rod", new AspectList().add(Aspects.AIR, 5).add(Aspects.MOTION, 4).add(Aspects.ENERGY, 2));
        r.item("minecraft:dragon_breath", new AspectList().add(Aspects.ELDRITCH, 4).add(Aspects.POISON, 4).add(Aspects.MAGIC, 4));
        r.item("minecraft:totem_of_undying", new AspectList().add(Aspects.LIFE, 6).add(Aspects.MAGIC, 6).add(Aspects.GREED, 4));
        r.item("minecraft:trident", new AspectList().add(Aspects.WEAPON, 4).add(Aspects.WATER, 4).add(Aspects.METAL, 2).add(Aspects.MAGIC, 2));
        r.item("minecraft:goat_horn", new AspectList().add(Aspects.BEAST, 2).add(Aspects.SENSES, 3).add(Aspects.AIR, 2));
        r.item("minecraft:turtle_egg", new AspectList().add(Aspects.LIFE, 3).add(Aspects.BEAST, 2));
        r.item("minecraft:sniffer_egg", new AspectList().add(Aspects.LIFE, 3).add(Aspects.BEAST, 2));
        r.item("minecraft:blue_egg", new AspectList().add(Aspects.LIFE, 2).add(Aspects.BEAST, 1));
        r.item("minecraft:brown_egg", new AspectList().add(Aspects.LIFE, 2).add(Aspects.BEAST, 1));
        r.item("minecraft:dragon_head", new AspectList().add(Aspects.DEATH, 4).add(Aspects.SOUL, 4).add(Aspects.BEAST, 2));
        r.item("minecraft:piglin_head", new AspectList().add(Aspects.DEATH, 4).add(Aspects.SOUL, 4).add(Aspects.BEAST, 2));
        r.item("minecraft:resin_clump", new AspectList().add(Aspects.TREE, 2).add(Aspects.SLIME, 2));
        r.item("minecraft:resin_brick", new AspectList().add(Aspects.TREE, 2).add(Aspects.CRAFT, 1));
        r.item("minecraft:powder_snow_bucket", new AspectList().add(Aspects.METAL, 3).add(Aspects.COLD, 4).add(Aspects.WATER, 2));
        r.item("minecraft:pufferfish_bucket", new AspectList().add(Aspects.METAL, 3).add(Aspects.WATER, 3).add(Aspects.BEAST, 2).add(Aspects.POISON, 2));
        r.item("minecraft:salmon_bucket", new AspectList().add(Aspects.METAL, 3).add(Aspects.WATER, 3).add(Aspects.BEAST, 2).add(Aspects.FLESH, 1));
        r.item("minecraft:cod_bucket", new AspectList().add(Aspects.METAL, 3).add(Aspects.WATER, 3).add(Aspects.BEAST, 2).add(Aspects.FLESH, 1));
        r.item("minecraft:tropical_fish_bucket", new AspectList().add(Aspects.METAL, 3).add(Aspects.WATER, 3).add(Aspects.BEAST, 2).add(Aspects.SENSES, 1));
        r.item("minecraft:axolotl_bucket", new AspectList().add(Aspects.METAL, 3).add(Aspects.WATER, 3).add(Aspects.BEAST, 2).add(Aspects.HEAL, 2));
        r.item("minecraft:tadpole_bucket", new AspectList().add(Aspects.METAL, 3).add(Aspects.WATER, 3).add(Aspects.BEAST, 2).add(Aspects.LIFE, 1));
        r.item("minecraft:sulfur_cube_bucket", new AspectList().add(Aspects.METAL, 3).add(Aspects.WATER, 2).add(Aspects.FIRE, 3).add(Aspects.POISON, 2));
        r.item("minecraft:white_shulker_box", new AspectList().add(Aspects.VOID, 3).add(Aspects.ARMOR, 2).add(Aspects.ELDRITCH, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:orange_shulker_box", new AspectList().add(Aspects.VOID, 3).add(Aspects.ARMOR, 2).add(Aspects.ELDRITCH, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:magenta_shulker_box", new AspectList().add(Aspects.VOID, 3).add(Aspects.ARMOR, 2).add(Aspects.ELDRITCH, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:light_blue_shulker_box", new AspectList().add(Aspects.VOID, 3).add(Aspects.ARMOR, 2).add(Aspects.ELDRITCH, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:yellow_shulker_box", new AspectList().add(Aspects.VOID, 3).add(Aspects.ARMOR, 2).add(Aspects.ELDRITCH, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:lime_shulker_box", new AspectList().add(Aspects.VOID, 3).add(Aspects.ARMOR, 2).add(Aspects.ELDRITCH, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:pink_shulker_box", new AspectList().add(Aspects.VOID, 3).add(Aspects.ARMOR, 2).add(Aspects.ELDRITCH, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:gray_shulker_box", new AspectList().add(Aspects.VOID, 3).add(Aspects.ARMOR, 2).add(Aspects.ELDRITCH, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:light_gray_shulker_box", new AspectList().add(Aspects.VOID, 3).add(Aspects.ARMOR, 2).add(Aspects.ELDRITCH, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:cyan_shulker_box", new AspectList().add(Aspects.VOID, 3).add(Aspects.ARMOR, 2).add(Aspects.ELDRITCH, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:purple_shulker_box", new AspectList().add(Aspects.VOID, 3).add(Aspects.ARMOR, 2).add(Aspects.ELDRITCH, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:blue_shulker_box", new AspectList().add(Aspects.VOID, 3).add(Aspects.ARMOR, 2).add(Aspects.ELDRITCH, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:brown_shulker_box", new AspectList().add(Aspects.VOID, 3).add(Aspects.ARMOR, 2).add(Aspects.ELDRITCH, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:green_shulker_box", new AspectList().add(Aspects.VOID, 3).add(Aspects.ARMOR, 2).add(Aspects.ELDRITCH, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:red_shulker_box", new AspectList().add(Aspects.VOID, 3).add(Aspects.ARMOR, 2).add(Aspects.ELDRITCH, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:black_shulker_box", new AspectList().add(Aspects.VOID, 3).add(Aspects.ARMOR, 2).add(Aspects.ELDRITCH, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:white_glazed_terracotta", new AspectList().add(Aspects.EARTH, 2).add(Aspects.FIRE, 1).add(Aspects.SENSES, 2));
        r.item("minecraft:white_concrete", new AspectList().add(Aspects.EARTH, 2).add(Aspects.WATER, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:white_bundle", new AspectList().add(Aspects.CLOTH, 2).add(Aspects.VOID, 2).add(Aspects.SENSES, 1));
        r.item("minecraft:orange_glazed_terracotta", new AspectList().add(Aspects.EARTH, 2).add(Aspects.FIRE, 1).add(Aspects.SENSES, 2));
        r.item("minecraft:orange_concrete", new AspectList().add(Aspects.EARTH, 2).add(Aspects.WATER, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:orange_bundle", new AspectList().add(Aspects.CLOTH, 2).add(Aspects.VOID, 2).add(Aspects.SENSES, 1));
        r.item("minecraft:magenta_glazed_terracotta", new AspectList().add(Aspects.EARTH, 2).add(Aspects.FIRE, 1).add(Aspects.SENSES, 2));
        r.item("minecraft:magenta_concrete", new AspectList().add(Aspects.EARTH, 2).add(Aspects.WATER, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:magenta_bundle", new AspectList().add(Aspects.CLOTH, 2).add(Aspects.VOID, 2).add(Aspects.SENSES, 1));
        r.item("minecraft:light_blue_glazed_terracotta", new AspectList().add(Aspects.EARTH, 2).add(Aspects.FIRE, 1).add(Aspects.SENSES, 2));
        r.item("minecraft:light_blue_concrete", new AspectList().add(Aspects.EARTH, 2).add(Aspects.WATER, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:light_blue_bundle", new AspectList().add(Aspects.CLOTH, 2).add(Aspects.VOID, 2).add(Aspects.SENSES, 1));
        r.item("minecraft:yellow_glazed_terracotta", new AspectList().add(Aspects.EARTH, 2).add(Aspects.FIRE, 1).add(Aspects.SENSES, 2));
        r.item("minecraft:yellow_concrete", new AspectList().add(Aspects.EARTH, 2).add(Aspects.WATER, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:yellow_bundle", new AspectList().add(Aspects.CLOTH, 2).add(Aspects.VOID, 2).add(Aspects.SENSES, 1));
        r.item("minecraft:lime_glazed_terracotta", new AspectList().add(Aspects.EARTH, 2).add(Aspects.FIRE, 1).add(Aspects.SENSES, 2));
        r.item("minecraft:lime_concrete", new AspectList().add(Aspects.EARTH, 2).add(Aspects.WATER, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:lime_bundle", new AspectList().add(Aspects.CLOTH, 2).add(Aspects.VOID, 2).add(Aspects.SENSES, 1));
        r.item("minecraft:pink_glazed_terracotta", new AspectList().add(Aspects.EARTH, 2).add(Aspects.FIRE, 1).add(Aspects.SENSES, 2));
        r.item("minecraft:pink_concrete", new AspectList().add(Aspects.EARTH, 2).add(Aspects.WATER, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:pink_bundle", new AspectList().add(Aspects.CLOTH, 2).add(Aspects.VOID, 2).add(Aspects.SENSES, 1));
        r.item("minecraft:gray_glazed_terracotta", new AspectList().add(Aspects.EARTH, 2).add(Aspects.FIRE, 1).add(Aspects.SENSES, 2));
        r.item("minecraft:gray_concrete", new AspectList().add(Aspects.EARTH, 2).add(Aspects.WATER, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:gray_bundle", new AspectList().add(Aspects.CLOTH, 2).add(Aspects.VOID, 2).add(Aspects.SENSES, 1));
        r.item("minecraft:light_gray_glazed_terracotta", new AspectList().add(Aspects.EARTH, 2).add(Aspects.FIRE, 1).add(Aspects.SENSES, 2));
        r.item("minecraft:light_gray_concrete", new AspectList().add(Aspects.EARTH, 2).add(Aspects.WATER, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:light_gray_bundle", new AspectList().add(Aspects.CLOTH, 2).add(Aspects.VOID, 2).add(Aspects.SENSES, 1));
        r.item("minecraft:cyan_glazed_terracotta", new AspectList().add(Aspects.EARTH, 2).add(Aspects.FIRE, 1).add(Aspects.SENSES, 2));
        r.item("minecraft:cyan_concrete", new AspectList().add(Aspects.EARTH, 2).add(Aspects.WATER, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:cyan_bundle", new AspectList().add(Aspects.CLOTH, 2).add(Aspects.VOID, 2).add(Aspects.SENSES, 1));
        r.item("minecraft:purple_glazed_terracotta", new AspectList().add(Aspects.EARTH, 2).add(Aspects.FIRE, 1).add(Aspects.SENSES, 2));
        r.item("minecraft:purple_concrete", new AspectList().add(Aspects.EARTH, 2).add(Aspects.WATER, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:purple_bundle", new AspectList().add(Aspects.CLOTH, 2).add(Aspects.VOID, 2).add(Aspects.SENSES, 1));
        r.item("minecraft:blue_glazed_terracotta", new AspectList().add(Aspects.EARTH, 2).add(Aspects.FIRE, 1).add(Aspects.SENSES, 2));
        r.item("minecraft:blue_concrete", new AspectList().add(Aspects.EARTH, 2).add(Aspects.WATER, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:blue_bundle", new AspectList().add(Aspects.CLOTH, 2).add(Aspects.VOID, 2).add(Aspects.SENSES, 1));
        r.item("minecraft:brown_glazed_terracotta", new AspectList().add(Aspects.EARTH, 2).add(Aspects.FIRE, 1).add(Aspects.SENSES, 2));
        r.item("minecraft:brown_concrete", new AspectList().add(Aspects.EARTH, 2).add(Aspects.WATER, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:brown_bundle", new AspectList().add(Aspects.CLOTH, 2).add(Aspects.VOID, 2).add(Aspects.SENSES, 1));
        r.item("minecraft:green_glazed_terracotta", new AspectList().add(Aspects.EARTH, 2).add(Aspects.FIRE, 1).add(Aspects.SENSES, 2));
        r.item("minecraft:green_concrete", new AspectList().add(Aspects.EARTH, 2).add(Aspects.WATER, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:green_bundle", new AspectList().add(Aspects.CLOTH, 2).add(Aspects.VOID, 2).add(Aspects.SENSES, 1));
        r.item("minecraft:red_glazed_terracotta", new AspectList().add(Aspects.EARTH, 2).add(Aspects.FIRE, 1).add(Aspects.SENSES, 2));
        r.item("minecraft:red_concrete", new AspectList().add(Aspects.EARTH, 2).add(Aspects.WATER, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:red_bundle", new AspectList().add(Aspects.CLOTH, 2).add(Aspects.VOID, 2).add(Aspects.SENSES, 1));
        r.item("minecraft:black_glazed_terracotta", new AspectList().add(Aspects.EARTH, 2).add(Aspects.FIRE, 1).add(Aspects.SENSES, 2));
        r.item("minecraft:black_concrete", new AspectList().add(Aspects.EARTH, 2).add(Aspects.WATER, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:black_bundle", new AspectList().add(Aspects.CLOTH, 2).add(Aspects.VOID, 2).add(Aspects.SENSES, 1));
        r.item("minecraft:experience_bottle", new AspectList().add(Aspects.MAGIC, 4).add(Aspects.ENERGY, 4).add(Aspects.MIND, 2));
        r.item("minecraft:written_book", new AspectList().add(Aspects.MIND, 4).add(Aspects.CRAFT, 1));
        r.item("minecraft:firework_star", new AspectList().add(Aspects.FIRE, 2).add(Aspects.SENSES, 4).add(Aspects.ENERGY, 1));
        r.item("minecraft:tipped_arrow", new AspectList().add(Aspects.WEAPON, 2).add(Aspects.MOTION, 2).add(Aspects.POISON, 2));
        r.item("minecraft:netherite_spear", new AspectList().add(Aspects.WEAPON, 5).add(Aspects.METAL, 5).add(Aspects.MOTION, 2));
        r.item("minecraft:bell", new AspectList().add(Aspects.METAL, 4).add(Aspects.SENSES, 4));
        r.item("minecraft:globe_banner_pattern", new AspectList().add(Aspects.CLOTH, 1).add(Aspects.SENSES, 2).add(Aspects.CRAFT, 1));
        r.item("minecraft:piglin_banner_pattern", new AspectList().add(Aspects.CLOTH, 1).add(Aspects.SENSES, 2).add(Aspects.CRAFT, 1));
        r.item("minecraft:flow_banner_pattern", new AspectList().add(Aspects.CLOTH, 1).add(Aspects.SENSES, 2).add(Aspects.CRAFT, 1));
        r.item("minecraft:guster_banner_pattern", new AspectList().add(Aspects.CLOTH, 1).add(Aspects.SENSES, 2).add(Aspects.CRAFT, 1));
        r.item("minecraft:angler_pottery_sherd", new AspectList().add(Aspects.EARTH, 1).add(Aspects.SENSES, 2).add(Aspects.MIND, 1));
        r.item("minecraft:archer_pottery_sherd", new AspectList().add(Aspects.EARTH, 1).add(Aspects.SENSES, 2).add(Aspects.MIND, 1));
        r.item("minecraft:arms_up_pottery_sherd", new AspectList().add(Aspects.EARTH, 1).add(Aspects.SENSES, 2).add(Aspects.MIND, 1));
        r.item("minecraft:blade_pottery_sherd", new AspectList().add(Aspects.EARTH, 1).add(Aspects.SENSES, 2).add(Aspects.MIND, 1));
        r.item("minecraft:brewer_pottery_sherd", new AspectList().add(Aspects.EARTH, 1).add(Aspects.SENSES, 2).add(Aspects.MIND, 1));
        r.item("minecraft:burn_pottery_sherd", new AspectList().add(Aspects.EARTH, 1).add(Aspects.SENSES, 2).add(Aspects.MIND, 1));
        r.item("minecraft:danger_pottery_sherd", new AspectList().add(Aspects.EARTH, 1).add(Aspects.SENSES, 2).add(Aspects.MIND, 1));
        r.item("minecraft:explorer_pottery_sherd", new AspectList().add(Aspects.EARTH, 1).add(Aspects.SENSES, 2).add(Aspects.MIND, 1));
        r.item("minecraft:flow_pottery_sherd", new AspectList().add(Aspects.EARTH, 1).add(Aspects.SENSES, 2).add(Aspects.MIND, 1));
        r.item("minecraft:friend_pottery_sherd", new AspectList().add(Aspects.EARTH, 1).add(Aspects.SENSES, 2).add(Aspects.MIND, 1));
        r.item("minecraft:guster_pottery_sherd", new AspectList().add(Aspects.EARTH, 1).add(Aspects.SENSES, 2).add(Aspects.MIND, 1));
        r.item("minecraft:heart_pottery_sherd", new AspectList().add(Aspects.EARTH, 1).add(Aspects.SENSES, 2).add(Aspects.MIND, 1));
        r.item("minecraft:heartbreak_pottery_sherd", new AspectList().add(Aspects.EARTH, 1).add(Aspects.SENSES, 2).add(Aspects.MIND, 1));
        r.item("minecraft:howl_pottery_sherd", new AspectList().add(Aspects.EARTH, 1).add(Aspects.SENSES, 2).add(Aspects.MIND, 1));
        r.item("minecraft:miner_pottery_sherd", new AspectList().add(Aspects.EARTH, 1).add(Aspects.SENSES, 2).add(Aspects.MIND, 1));
        r.item("minecraft:mourner_pottery_sherd", new AspectList().add(Aspects.EARTH, 1).add(Aspects.SENSES, 2).add(Aspects.MIND, 1));
        r.item("minecraft:plenty_pottery_sherd", new AspectList().add(Aspects.EARTH, 1).add(Aspects.SENSES, 2).add(Aspects.MIND, 1));
        r.item("minecraft:prize_pottery_sherd", new AspectList().add(Aspects.EARTH, 1).add(Aspects.SENSES, 2).add(Aspects.MIND, 1));
        r.item("minecraft:scrape_pottery_sherd", new AspectList().add(Aspects.EARTH, 1).add(Aspects.SENSES, 2).add(Aspects.MIND, 1));
        r.item("minecraft:sheaf_pottery_sherd", new AspectList().add(Aspects.EARTH, 1).add(Aspects.SENSES, 2).add(Aspects.MIND, 1));
        r.item("minecraft:shelter_pottery_sherd", new AspectList().add(Aspects.EARTH, 1).add(Aspects.SENSES, 2).add(Aspects.MIND, 1));
        r.item("minecraft:skull_pottery_sherd", new AspectList().add(Aspects.EARTH, 1).add(Aspects.SENSES, 2).add(Aspects.MIND, 1));
        r.item("minecraft:snort_pottery_sherd", new AspectList().add(Aspects.EARTH, 1).add(Aspects.SENSES, 2).add(Aspects.MIND, 1));
        r.item("minecraft:trial_spawner", new AspectList().add(Aspects.EARTH, 2).add(Aspects.MAGIC, 4).add(Aspects.TRAP, 4).add(Aspects.BEAST, 2));
        r.item("minecraft:vault", new AspectList().add(Aspects.EARTH, 2).add(Aspects.MAGIC, 4).add(Aspects.GREED, 4).add(Aspects.VOID, 2));
        r.item("minecraft:trial_key", new AspectList().add(Aspects.METAL, 2).add(Aspects.MAGIC, 2).add(Aspects.GREED, 2));
        r.item("minecraft:ominous_trial_key", new AspectList().add(Aspects.METAL, 2).add(Aspects.MAGIC, 4).add(Aspects.GREED, 3).add(Aspects.DARKNESS, 2));
        r.item("minecraft:ominous_bottle", new AspectList().add(Aspects.MAGIC, 4).add(Aspects.DARKNESS, 3).add(Aspects.TRAP, 2));
        r.item("minecraft:music_disc_bounce", new AspectList().add(Aspects.SENSES, 4).add(Aspects.AIR, 4).add(Aspects.GREED, 4));
        r.item("minecraft:music_disc_creator", new AspectList().add(Aspects.SENSES, 4).add(Aspects.AIR, 4).add(Aspects.GREED, 4));
        r.item("minecraft:music_disc_creator_music_box", new AspectList().add(Aspects.SENSES, 4).add(Aspects.AIR, 4).add(Aspects.GREED, 4));
        r.item("minecraft:music_disc_lava_chicken", new AspectList().add(Aspects.SENSES, 4).add(Aspects.AIR, 4).add(Aspects.GREED, 4));
        r.item("minecraft:music_disc_otherside", new AspectList().add(Aspects.SENSES, 4).add(Aspects.AIR, 4).add(Aspects.GREED, 4));
        r.item("minecraft:music_disc_relic", new AspectList().add(Aspects.SENSES, 4).add(Aspects.AIR, 4).add(Aspects.GREED, 4));
        r.item("minecraft:music_disc_5", new AspectList().add(Aspects.SENSES, 4).add(Aspects.AIR, 4).add(Aspects.GREED, 4));
        r.item("minecraft:music_disc_pigstep", new AspectList().add(Aspects.SENSES, 4).add(Aspects.AIR, 4).add(Aspects.GREED, 4));
        r.item("minecraft:music_disc_precipice", new AspectList().add(Aspects.SENSES, 4).add(Aspects.AIR, 4).add(Aspects.GREED, 4));
        r.item("minecraft:music_disc_tears", new AspectList().add(Aspects.SENSES, 4).add(Aspects.AIR, 4).add(Aspects.GREED, 4));
        r.item("minecraft:disc_fragment_5", new AspectList().add(Aspects.SENSES, 2).add(Aspects.AIR, 2).add(Aspects.ENTROPY, 2));
        r.item("minecraft:raw_iron", new AspectList().add(Aspects.METAL, 3).add(Aspects.EARTH, 1));
        r.item("minecraft:raw_gold", new AspectList().add(Aspects.METAL, 3).add(Aspects.EARTH, 1));
        r.item("minecraft:raw_copper", new AspectList().add(Aspects.METAL, 2).add(Aspects.EARTH, 1).add(Aspects.EXCHANGE, 1));
        r.item("minecraft:polished_deepslate", new AspectList().add(Aspects.EARTH, 2).add(Aspects.DARKNESS, 1));
        r.item("minecraft:deepslate_bricks", new AspectList().add(Aspects.EARTH, 2).add(Aspects.DARKNESS, 1));
        r.item("minecraft:deepslate_tiles", new AspectList().add(Aspects.EARTH, 2).add(Aspects.DARKNESS, 1));
        r.item("minecraft:tuff_bricks", new AspectList().add(Aspects.EARTH, 2));
        r.item("minecraft:mud_bricks", new AspectList().add(Aspects.EARTH, 2));
        r.item("minecraft:end_stone_bricks", new AspectList().add(Aspects.EARTH, 2));
        r.item("minecraft:polished_blackstone_bricks", new AspectList().add(Aspects.EARTH, 2));
        r.item("minecraft:sulfur_bricks", new AspectList().add(Aspects.EARTH, 2));
        r.item("minecraft:cinnabar_bricks", new AspectList().add(Aspects.EARTH, 2));
        r.item("minecraft:copper_bars", new AspectList().add(Aspects.METAL, 2));
        r.item("minecraft:end_rod", new AspectList().add(Aspects.LIGHT, 4).add(Aspects.ELDRITCH, 1));
        r.item("minecraft:soul_torch", new AspectList().add(Aspects.LIGHT, 2).add(Aspects.SOUL, 2));
        r.item("minecraft:copper_torch", new AspectList().add(Aspects.LIGHT, 2).add(Aspects.METAL, 1));
        r.item("minecraft:scaffolding", new AspectList().add(Aspects.TREE, 1).add(Aspects.TRAVEL, 1));
        r.item("minecraft:honey_block", new AspectList().add(Aspects.CROP, 2).add(Aspects.SLIME, 2).add(Aspects.BEAST, 1));
        r.item("minecraft:honey_bottle", new AspectList().add(Aspects.CROP, 2).add(Aspects.HUNGER, 2).add(Aspects.HEAL, 1));
        r.item("minecraft:sugar", new AspectList().add(Aspects.CROP, 1).add(Aspects.HUNGER, 1));
        r.item("minecraft:dried_kelp", new AspectList().add(Aspects.PLANT, 1).add(Aspects.HUNGER, 1));
        r.item("minecraft:dried_kelp_block", new AspectList().add(Aspects.PLANT, 2).add(Aspects.HUNGER, 2).add(Aspects.FIRE, 1));
        r.item("minecraft:wind_charge", new AspectList().add(Aspects.AIR, 4).add(Aspects.MOTION, 3).add(Aspects.WEAPON, 1));
        r.item("minecraft:filled_map", new AspectList().add(Aspects.MIND, 2).add(Aspects.SENSES, 2).add(Aspects.TRAVEL, 2));
        r.item("minecraft:flower_banner_pattern", new AspectList().add(Aspects.CLOTH, 1).add(Aspects.SENSES, 2).add(Aspects.CRAFT, 1));
        r.item("minecraft:bordure_indented_banner_pattern", new AspectList().add(Aspects.CLOTH, 1).add(Aspects.SENSES, 2).add(Aspects.CRAFT, 1));
        r.item("minecraft:white_candle", new AspectList().add(Aspects.LIGHT, 2).add(Aspects.CLOTH, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:orange_candle", new AspectList().add(Aspects.LIGHT, 2).add(Aspects.CLOTH, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:magenta_candle", new AspectList().add(Aspects.LIGHT, 2).add(Aspects.CLOTH, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:light_blue_candle", new AspectList().add(Aspects.LIGHT, 2).add(Aspects.CLOTH, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:yellow_candle", new AspectList().add(Aspects.LIGHT, 2).add(Aspects.CLOTH, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:lime_candle", new AspectList().add(Aspects.LIGHT, 2).add(Aspects.CLOTH, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:pink_candle", new AspectList().add(Aspects.LIGHT, 2).add(Aspects.CLOTH, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:gray_candle", new AspectList().add(Aspects.LIGHT, 2).add(Aspects.CLOTH, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:light_gray_candle", new AspectList().add(Aspects.LIGHT, 2).add(Aspects.CLOTH, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:cyan_candle", new AspectList().add(Aspects.LIGHT, 2).add(Aspects.CLOTH, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:purple_candle", new AspectList().add(Aspects.LIGHT, 2).add(Aspects.CLOTH, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:blue_candle", new AspectList().add(Aspects.LIGHT, 2).add(Aspects.CLOTH, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:brown_candle", new AspectList().add(Aspects.LIGHT, 2).add(Aspects.CLOTH, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:green_candle", new AspectList().add(Aspects.LIGHT, 2).add(Aspects.CLOTH, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:red_candle", new AspectList().add(Aspects.LIGHT, 2).add(Aspects.CLOTH, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:black_candle", new AspectList().add(Aspects.LIGHT, 2).add(Aspects.CLOTH, 1).add(Aspects.SENSES, 1));
        r.item("minecraft:polished_blackstone_button", new AspectList().add(Aspects.EARTH, 1).add(Aspects.MECHANISM, 1));
        r.item("minecraft:spruce_button", new AspectList().add(Aspects.TREE, 1).add(Aspects.MECHANISM, 1));
        r.item("minecraft:birch_button", new AspectList().add(Aspects.TREE, 1).add(Aspects.MECHANISM, 1));
        r.item("minecraft:jungle_button", new AspectList().add(Aspects.TREE, 1).add(Aspects.MECHANISM, 1));
        r.item("minecraft:acacia_button", new AspectList().add(Aspects.TREE, 1).add(Aspects.MECHANISM, 1));
        r.item("minecraft:cherry_button", new AspectList().add(Aspects.TREE, 1).add(Aspects.MECHANISM, 1));
        r.item("minecraft:dark_oak_button", new AspectList().add(Aspects.TREE, 1).add(Aspects.MECHANISM, 1));
        r.item("minecraft:pale_oak_button", new AspectList().add(Aspects.TREE, 1).add(Aspects.MECHANISM, 1));
        r.item("minecraft:mangrove_button", new AspectList().add(Aspects.TREE, 1).add(Aspects.MECHANISM, 1));
        r.item("minecraft:bamboo_button", new AspectList().add(Aspects.TREE, 1).add(Aspects.MECHANISM, 1));
        r.item("minecraft:crimson_button", new AspectList().add(Aspects.TREE, 1).add(Aspects.MECHANISM, 1));
        r.item("minecraft:warped_button", new AspectList().add(Aspects.TREE, 1).add(Aspects.MECHANISM, 1));
        r.tagIfAbsent("minecraft:slabs", new AspectList().add(Aspects.EARTH, 1));
        r.tagIfAbsent("minecraft:stairs", new AspectList().add(Aspects.EARTH, 1));
        r.tagIfAbsent("minecraft:walls", new AspectList().add(Aspects.EARTH, 1));
        r.tagIfAbsent("c:glass_panes", new AspectList().add(Aspects.CRYSTAL, 1));
        r.tagIfAbsent("minecraft:stone_bricks", new AspectList().add(Aspects.EARTH, 2));
    }
}
